// Code generated by ent, DO NOT EDIT.

package salesorder

import (
	"go-wind-erp/app/core/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEQ(FieldDeletedBy, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEQ(FieldRemark, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEQ(FieldTenantID, v))
}

// SoNumber applies equality check predicate on the "so_number" field. It's identical to SoNumberEQ.
func SoNumber(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEQ(FieldSoNumber, v))
}

// CustomerCode applies equality check predicate on the "customer_code" field. It's identical to CustomerCodeEQ.
func CustomerCode(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEQ(FieldCustomerCode, v))
}

// TotalAmount applies equality check predicate on the "total_amount" field. It's identical to TotalAmountEQ.
func TotalAmount(v int64) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEQ(FieldTotalAmount, v))
}

// WarehouseCode applies equality check predicate on the "warehouse_code" field. It's identical to WarehouseCodeEQ.
func WarehouseCode(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEQ(FieldWarehouseCode, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNotNull(FieldUpdatedBy))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNotNull(FieldDeletedBy))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldContainsFold(FieldRemark, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNotNull(FieldTenantID))
}

// SoNumberEQ applies the EQ predicate on the "so_number" field.
func SoNumberEQ(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEQ(FieldSoNumber, v))
}

// SoNumberNEQ applies the NEQ predicate on the "so_number" field.
func SoNumberNEQ(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNEQ(FieldSoNumber, v))
}

// SoNumberIn applies the In predicate on the "so_number" field.
func SoNumberIn(vs ...string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldIn(FieldSoNumber, vs...))
}

// SoNumberNotIn applies the NotIn predicate on the "so_number" field.
func SoNumberNotIn(vs ...string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNotIn(FieldSoNumber, vs...))
}

// SoNumberGT applies the GT predicate on the "so_number" field.
func SoNumberGT(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldGT(FieldSoNumber, v))
}

// SoNumberGTE applies the GTE predicate on the "so_number" field.
func SoNumberGTE(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldGTE(FieldSoNumber, v))
}

// SoNumberLT applies the LT predicate on the "so_number" field.
func SoNumberLT(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldLT(FieldSoNumber, v))
}

// SoNumberLTE applies the LTE predicate on the "so_number" field.
func SoNumberLTE(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldLTE(FieldSoNumber, v))
}

// SoNumberContains applies the Contains predicate on the "so_number" field.
func SoNumberContains(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldContains(FieldSoNumber, v))
}

// SoNumberHasPrefix applies the HasPrefix predicate on the "so_number" field.
func SoNumberHasPrefix(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldHasPrefix(FieldSoNumber, v))
}

// SoNumberHasSuffix applies the HasSuffix predicate on the "so_number" field.
func SoNumberHasSuffix(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldHasSuffix(FieldSoNumber, v))
}

// SoNumberIsNil applies the IsNil predicate on the "so_number" field.
func SoNumberIsNil() predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldIsNull(FieldSoNumber))
}

// SoNumberNotNil applies the NotNil predicate on the "so_number" field.
func SoNumberNotNil() predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNotNull(FieldSoNumber))
}

// SoNumberEqualFold applies the EqualFold predicate on the "so_number" field.
func SoNumberEqualFold(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEqualFold(FieldSoNumber, v))
}

// SoNumberContainsFold applies the ContainsFold predicate on the "so_number" field.
func SoNumberContainsFold(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldContainsFold(FieldSoNumber, v))
}

// CustomerCodeEQ applies the EQ predicate on the "customer_code" field.
func CustomerCodeEQ(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEQ(FieldCustomerCode, v))
}

// CustomerCodeNEQ applies the NEQ predicate on the "customer_code" field.
func CustomerCodeNEQ(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNEQ(FieldCustomerCode, v))
}

// CustomerCodeIn applies the In predicate on the "customer_code" field.
func CustomerCodeIn(vs ...string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldIn(FieldCustomerCode, vs...))
}

// CustomerCodeNotIn applies the NotIn predicate on the "customer_code" field.
func CustomerCodeNotIn(vs ...string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNotIn(FieldCustomerCode, vs...))
}

// CustomerCodeGT applies the GT predicate on the "customer_code" field.
func CustomerCodeGT(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldGT(FieldCustomerCode, v))
}

// CustomerCodeGTE applies the GTE predicate on the "customer_code" field.
func CustomerCodeGTE(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldGTE(FieldCustomerCode, v))
}

// CustomerCodeLT applies the LT predicate on the "customer_code" field.
func CustomerCodeLT(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldLT(FieldCustomerCode, v))
}

// CustomerCodeLTE applies the LTE predicate on the "customer_code" field.
func CustomerCodeLTE(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldLTE(FieldCustomerCode, v))
}

// CustomerCodeContains applies the Contains predicate on the "customer_code" field.
func CustomerCodeContains(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldContains(FieldCustomerCode, v))
}

// CustomerCodeHasPrefix applies the HasPrefix predicate on the "customer_code" field.
func CustomerCodeHasPrefix(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldHasPrefix(FieldCustomerCode, v))
}

// CustomerCodeHasSuffix applies the HasSuffix predicate on the "customer_code" field.
func CustomerCodeHasSuffix(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldHasSuffix(FieldCustomerCode, v))
}

// CustomerCodeIsNil applies the IsNil predicate on the "customer_code" field.
func CustomerCodeIsNil() predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldIsNull(FieldCustomerCode))
}

// CustomerCodeNotNil applies the NotNil predicate on the "customer_code" field.
func CustomerCodeNotNil() predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNotNull(FieldCustomerCode))
}

// CustomerCodeEqualFold applies the EqualFold predicate on the "customer_code" field.
func CustomerCodeEqualFold(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEqualFold(FieldCustomerCode, v))
}

// CustomerCodeContainsFold applies the ContainsFold predicate on the "customer_code" field.
func CustomerCodeContainsFold(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldContainsFold(FieldCustomerCode, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNotNull(FieldStatus))
}

// TotalAmountEQ applies the EQ predicate on the "total_amount" field.
func TotalAmountEQ(v int64) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEQ(FieldTotalAmount, v))
}

// TotalAmountNEQ applies the NEQ predicate on the "total_amount" field.
func TotalAmountNEQ(v int64) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNEQ(FieldTotalAmount, v))
}

// TotalAmountIn applies the In predicate on the "total_amount" field.
func TotalAmountIn(vs ...int64) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldIn(FieldTotalAmount, vs...))
}

// TotalAmountNotIn applies the NotIn predicate on the "total_amount" field.
func TotalAmountNotIn(vs ...int64) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNotIn(FieldTotalAmount, vs...))
}

// TotalAmountGT applies the GT predicate on the "total_amount" field.
func TotalAmountGT(v int64) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldGT(FieldTotalAmount, v))
}

// TotalAmountGTE applies the GTE predicate on the "total_amount" field.
func TotalAmountGTE(v int64) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldGTE(FieldTotalAmount, v))
}

// TotalAmountLT applies the LT predicate on the "total_amount" field.
func TotalAmountLT(v int64) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldLT(FieldTotalAmount, v))
}

// TotalAmountLTE applies the LTE predicate on the "total_amount" field.
func TotalAmountLTE(v int64) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldLTE(FieldTotalAmount, v))
}

// TotalAmountIsNil applies the IsNil predicate on the "total_amount" field.
func TotalAmountIsNil() predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldIsNull(FieldTotalAmount))
}

// TotalAmountNotNil applies the NotNil predicate on the "total_amount" field.
func TotalAmountNotNil() predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNotNull(FieldTotalAmount))
}

// WarehouseCodeEQ applies the EQ predicate on the "warehouse_code" field.
func WarehouseCodeEQ(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEQ(FieldWarehouseCode, v))
}

// WarehouseCodeNEQ applies the NEQ predicate on the "warehouse_code" field.
func WarehouseCodeNEQ(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNEQ(FieldWarehouseCode, v))
}

// WarehouseCodeIn applies the In predicate on the "warehouse_code" field.
func WarehouseCodeIn(vs ...string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldIn(FieldWarehouseCode, vs...))
}

// WarehouseCodeNotIn applies the NotIn predicate on the "warehouse_code" field.
func WarehouseCodeNotIn(vs ...string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNotIn(FieldWarehouseCode, vs...))
}

// WarehouseCodeGT applies the GT predicate on the "warehouse_code" field.
func WarehouseCodeGT(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldGT(FieldWarehouseCode, v))
}

// WarehouseCodeGTE applies the GTE predicate on the "warehouse_code" field.
func WarehouseCodeGTE(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldGTE(FieldWarehouseCode, v))
}

// WarehouseCodeLT applies the LT predicate on the "warehouse_code" field.
func WarehouseCodeLT(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldLT(FieldWarehouseCode, v))
}

// WarehouseCodeLTE applies the LTE predicate on the "warehouse_code" field.
func WarehouseCodeLTE(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldLTE(FieldWarehouseCode, v))
}

// WarehouseCodeContains applies the Contains predicate on the "warehouse_code" field.
func WarehouseCodeContains(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldContains(FieldWarehouseCode, v))
}

// WarehouseCodeHasPrefix applies the HasPrefix predicate on the "warehouse_code" field.
func WarehouseCodeHasPrefix(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldHasPrefix(FieldWarehouseCode, v))
}

// WarehouseCodeHasSuffix applies the HasSuffix predicate on the "warehouse_code" field.
func WarehouseCodeHasSuffix(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldHasSuffix(FieldWarehouseCode, v))
}

// WarehouseCodeIsNil applies the IsNil predicate on the "warehouse_code" field.
func WarehouseCodeIsNil() predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldIsNull(FieldWarehouseCode))
}

// WarehouseCodeNotNil applies the NotNil predicate on the "warehouse_code" field.
func WarehouseCodeNotNil() predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldNotNull(FieldWarehouseCode))
}

// WarehouseCodeEqualFold applies the EqualFold predicate on the "warehouse_code" field.
func WarehouseCodeEqualFold(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldEqualFold(FieldWarehouseCode, v))
}

// WarehouseCodeContainsFold applies the ContainsFold predicate on the "warehouse_code" field.
func WarehouseCodeContainsFold(v string) predicate.SalesOrder {
	return predicate.SalesOrder(sql.FieldContainsFold(FieldWarehouseCode, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SalesOrder) predicate.SalesOrder {
	return predicate.SalesOrder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SalesOrder) predicate.SalesOrder {
	return predicate.SalesOrder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SalesOrder) predicate.SalesOrder {
	return predicate.SalesOrder(sql.NotPredicates(p))
}
