// Code generated by ent, DO NOT EDIT.

package receivable

import (
	"go-wind-erp/app/core/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldDeletedBy, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldRemark, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldTenantID, v))
}

// ReceivableNumber applies equality check predicate on the "receivable_number" field. It's identical to ReceivableNumberEQ.
func ReceivableNumber(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldReceivableNumber, v))
}

// SoRef applies equality check predicate on the "so_ref" field. It's identical to SoRefEQ.
func SoRef(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldSoRef, v))
}

// CustomerCode applies equality check predicate on the "customer_code" field. It's identical to CustomerCodeEQ.
func CustomerCode(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldCustomerCode, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v int64) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldAmount, v))
}

// PaidAmount applies equality check predicate on the "paid_amount" field. It's identical to PaidAmountEQ.
func PaidAmount(v int64) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldPaidAmount, v))
}

// DueDate applies equality check predicate on the "due_date" field. It's identical to DueDateEQ.
func DueDate(v time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldDueDate, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldNotNull(FieldUpdatedBy))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldNotNull(FieldDeletedBy))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.Receivable {
	return predicate.Receivable(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.Receivable {
	return predicate.Receivable(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldContainsFold(FieldRemark, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.Receivable {
	return predicate.Receivable(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldNotNull(FieldTenantID))
}

// ReceivableNumberEQ applies the EQ predicate on the "receivable_number" field.
func ReceivableNumberEQ(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldReceivableNumber, v))
}

// ReceivableNumberNEQ applies the NEQ predicate on the "receivable_number" field.
func ReceivableNumberNEQ(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldNEQ(FieldReceivableNumber, v))
}

// ReceivableNumberIn applies the In predicate on the "receivable_number" field.
func ReceivableNumberIn(vs ...string) predicate.Receivable {
	return predicate.Receivable(sql.FieldIn(FieldReceivableNumber, vs...))
}

// ReceivableNumberNotIn applies the NotIn predicate on the "receivable_number" field.
func ReceivableNumberNotIn(vs ...string) predicate.Receivable {
	return predicate.Receivable(sql.FieldNotIn(FieldReceivableNumber, vs...))
}

// ReceivableNumberGT applies the GT predicate on the "receivable_number" field.
func ReceivableNumberGT(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldGT(FieldReceivableNumber, v))
}

// ReceivableNumberGTE applies the GTE predicate on the "receivable_number" field.
func ReceivableNumberGTE(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldGTE(FieldReceivableNumber, v))
}

// ReceivableNumberLT applies the LT predicate on the "receivable_number" field.
func ReceivableNumberLT(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldLT(FieldReceivableNumber, v))
}

// ReceivableNumberLTE applies the LTE predicate on the "receivable_number" field.
func ReceivableNumberLTE(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldLTE(FieldReceivableNumber, v))
}

// ReceivableNumberContains applies the Contains predicate on the "receivable_number" field.
func ReceivableNumberContains(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldContains(FieldReceivableNumber, v))
}

// ReceivableNumberHasPrefix applies the HasPrefix predicate on the "receivable_number" field.
func ReceivableNumberHasPrefix(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldHasPrefix(FieldReceivableNumber, v))
}

// ReceivableNumberHasSuffix applies the HasSuffix predicate on the "receivable_number" field.
func ReceivableNumberHasSuffix(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldHasSuffix(FieldReceivableNumber, v))
}

// ReceivableNumberIsNil applies the IsNil predicate on the "receivable_number" field.
func ReceivableNumberIsNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldIsNull(FieldReceivableNumber))
}

// ReceivableNumberNotNil applies the NotNil predicate on the "receivable_number" field.
func ReceivableNumberNotNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldNotNull(FieldReceivableNumber))
}

// ReceivableNumberEqualFold applies the EqualFold predicate on the "receivable_number" field.
func ReceivableNumberEqualFold(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldEqualFold(FieldReceivableNumber, v))
}

// ReceivableNumberContainsFold applies the ContainsFold predicate on the "receivable_number" field.
func ReceivableNumberContainsFold(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldContainsFold(FieldReceivableNumber, v))
}

// SoRefEQ applies the EQ predicate on the "so_ref" field.
func SoRefEQ(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldSoRef, v))
}

// SoRefNEQ applies the NEQ predicate on the "so_ref" field.
func SoRefNEQ(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldNEQ(FieldSoRef, v))
}

// SoRefIn applies the In predicate on the "so_ref" field.
func SoRefIn(vs ...string) predicate.Receivable {
	return predicate.Receivable(sql.FieldIn(FieldSoRef, vs...))
}

// SoRefNotIn applies the NotIn predicate on the "so_ref" field.
func SoRefNotIn(vs ...string) predicate.Receivable {
	return predicate.Receivable(sql.FieldNotIn(FieldSoRef, vs...))
}

// SoRefGT applies the GT predicate on the "so_ref" field.
func SoRefGT(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldGT(FieldSoRef, v))
}

// SoRefGTE applies the GTE predicate on the "so_ref" field.
func SoRefGTE(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldGTE(FieldSoRef, v))
}

// SoRefLT applies the LT predicate on the "so_ref" field.
func SoRefLT(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldLT(FieldSoRef, v))
}

// SoRefLTE applies the LTE predicate on the "so_ref" field.
func SoRefLTE(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldLTE(FieldSoRef, v))
}

// SoRefContains applies the Contains predicate on the "so_ref" field.
func SoRefContains(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldContains(FieldSoRef, v))
}

// SoRefHasPrefix applies the HasPrefix predicate on the "so_ref" field.
func SoRefHasPrefix(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldHasPrefix(FieldSoRef, v))
}

// SoRefHasSuffix applies the HasSuffix predicate on the "so_ref" field.
func SoRefHasSuffix(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldHasSuffix(FieldSoRef, v))
}

// SoRefIsNil applies the IsNil predicate on the "so_ref" field.
func SoRefIsNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldIsNull(FieldSoRef))
}

// SoRefNotNil applies the NotNil predicate on the "so_ref" field.
func SoRefNotNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldNotNull(FieldSoRef))
}

// SoRefEqualFold applies the EqualFold predicate on the "so_ref" field.
func SoRefEqualFold(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldEqualFold(FieldSoRef, v))
}

// SoRefContainsFold applies the ContainsFold predicate on the "so_ref" field.
func SoRefContainsFold(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldContainsFold(FieldSoRef, v))
}

// CustomerCodeEQ applies the EQ predicate on the "customer_code" field.
func CustomerCodeEQ(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldCustomerCode, v))
}

// CustomerCodeNEQ applies the NEQ predicate on the "customer_code" field.
func CustomerCodeNEQ(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldNEQ(FieldCustomerCode, v))
}

// CustomerCodeIn applies the In predicate on the "customer_code" field.
func CustomerCodeIn(vs ...string) predicate.Receivable {
	return predicate.Receivable(sql.FieldIn(FieldCustomerCode, vs...))
}

// CustomerCodeNotIn applies the NotIn predicate on the "customer_code" field.
func CustomerCodeNotIn(vs ...string) predicate.Receivable {
	return predicate.Receivable(sql.FieldNotIn(FieldCustomerCode, vs...))
}

// CustomerCodeGT applies the GT predicate on the "customer_code" field.
func CustomerCodeGT(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldGT(FieldCustomerCode, v))
}

// CustomerCodeGTE applies the GTE predicate on the "customer_code" field.
func CustomerCodeGTE(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldGTE(FieldCustomerCode, v))
}

// CustomerCodeLT applies the LT predicate on the "customer_code" field.
func CustomerCodeLT(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldLT(FieldCustomerCode, v))
}

// CustomerCodeLTE applies the LTE predicate on the "customer_code" field.
func CustomerCodeLTE(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldLTE(FieldCustomerCode, v))
}

// CustomerCodeContains applies the Contains predicate on the "customer_code" field.
func CustomerCodeContains(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldContains(FieldCustomerCode, v))
}

// CustomerCodeHasPrefix applies the HasPrefix predicate on the "customer_code" field.
func CustomerCodeHasPrefix(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldHasPrefix(FieldCustomerCode, v))
}

// CustomerCodeHasSuffix applies the HasSuffix predicate on the "customer_code" field.
func CustomerCodeHasSuffix(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldHasSuffix(FieldCustomerCode, v))
}

// CustomerCodeIsNil applies the IsNil predicate on the "customer_code" field.
func CustomerCodeIsNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldIsNull(FieldCustomerCode))
}

// CustomerCodeNotNil applies the NotNil predicate on the "customer_code" field.
func CustomerCodeNotNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldNotNull(FieldCustomerCode))
}

// CustomerCodeEqualFold applies the EqualFold predicate on the "customer_code" field.
func CustomerCodeEqualFold(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldEqualFold(FieldCustomerCode, v))
}

// CustomerCodeContainsFold applies the ContainsFold predicate on the "customer_code" field.
func CustomerCodeContainsFold(v string) predicate.Receivable {
	return predicate.Receivable(sql.FieldContainsFold(FieldCustomerCode, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v int64) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v int64) predicate.Receivable {
	return predicate.Receivable(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...int64) predicate.Receivable {
	return predicate.Receivable(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...int64) predicate.Receivable {
	return predicate.Receivable(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v int64) predicate.Receivable {
	return predicate.Receivable(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v int64) predicate.Receivable {
	return predicate.Receivable(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v int64) predicate.Receivable {
	return predicate.Receivable(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v int64) predicate.Receivable {
	return predicate.Receivable(sql.FieldLTE(FieldAmount, v))
}

// AmountIsNil applies the IsNil predicate on the "amount" field.
func AmountIsNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldIsNull(FieldAmount))
}

// AmountNotNil applies the NotNil predicate on the "amount" field.
func AmountNotNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldNotNull(FieldAmount))
}

// PaidAmountEQ applies the EQ predicate on the "paid_amount" field.
func PaidAmountEQ(v int64) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldPaidAmount, v))
}

// PaidAmountNEQ applies the NEQ predicate on the "paid_amount" field.
func PaidAmountNEQ(v int64) predicate.Receivable {
	return predicate.Receivable(sql.FieldNEQ(FieldPaidAmount, v))
}

// PaidAmountIn applies the In predicate on the "paid_amount" field.
func PaidAmountIn(vs ...int64) predicate.Receivable {
	return predicate.Receivable(sql.FieldIn(FieldPaidAmount, vs...))
}

// PaidAmountNotIn applies the NotIn predicate on the "paid_amount" field.
func PaidAmountNotIn(vs ...int64) predicate.Receivable {
	return predicate.Receivable(sql.FieldNotIn(FieldPaidAmount, vs...))
}

// PaidAmountGT applies the GT predicate on the "paid_amount" field.
func PaidAmountGT(v int64) predicate.Receivable {
	return predicate.Receivable(sql.FieldGT(FieldPaidAmount, v))
}

// PaidAmountGTE applies the GTE predicate on the "paid_amount" field.
func PaidAmountGTE(v int64) predicate.Receivable {
	return predicate.Receivable(sql.FieldGTE(FieldPaidAmount, v))
}

// PaidAmountLT applies the LT predicate on the "paid_amount" field.
func PaidAmountLT(v int64) predicate.Receivable {
	return predicate.Receivable(sql.FieldLT(FieldPaidAmount, v))
}

// PaidAmountLTE applies the LTE predicate on the "paid_amount" field.
func PaidAmountLTE(v int64) predicate.Receivable {
	return predicate.Receivable(sql.FieldLTE(FieldPaidAmount, v))
}

// PaidAmountIsNil applies the IsNil predicate on the "paid_amount" field.
func PaidAmountIsNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldIsNull(FieldPaidAmount))
}

// PaidAmountNotNil applies the NotNil predicate on the "paid_amount" field.
func PaidAmountNotNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldNotNull(FieldPaidAmount))
}

// DueDateEQ applies the EQ predicate on the "due_date" field.
func DueDateEQ(v time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldDueDate, v))
}

// DueDateNEQ applies the NEQ predicate on the "due_date" field.
func DueDateNEQ(v time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldNEQ(FieldDueDate, v))
}

// DueDateIn applies the In predicate on the "due_date" field.
func DueDateIn(vs ...time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldIn(FieldDueDate, vs...))
}

// DueDateNotIn applies the NotIn predicate on the "due_date" field.
func DueDateNotIn(vs ...time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldNotIn(FieldDueDate, vs...))
}

// DueDateGT applies the GT predicate on the "due_date" field.
func DueDateGT(v time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldGT(FieldDueDate, v))
}

// DueDateGTE applies the GTE predicate on the "due_date" field.
func DueDateGTE(v time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldGTE(FieldDueDate, v))
}

// DueDateLT applies the LT predicate on the "due_date" field.
func DueDateLT(v time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldLT(FieldDueDate, v))
}

// DueDateLTE applies the LTE predicate on the "due_date" field.
func DueDateLTE(v time.Time) predicate.Receivable {
	return predicate.Receivable(sql.FieldLTE(FieldDueDate, v))
}

// DueDateIsNil applies the IsNil predicate on the "due_date" field.
func DueDateIsNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldIsNull(FieldDueDate))
}

// DueDateNotNil applies the NotNil predicate on the "due_date" field.
func DueDateNotNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldNotNull(FieldDueDate))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Receivable {
	return predicate.Receivable(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Receivable {
	return predicate.Receivable(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Receivable {
	return predicate.Receivable(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Receivable {
	return predicate.Receivable(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.Receivable {
	return predicate.Receivable(sql.FieldNotNull(FieldStatus))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Receivable) predicate.Receivable {
	return predicate.Receivable(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Receivable) predicate.Receivable {
	return predicate.Receivable(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Receivable) predicate.Receivable {
	return predicate.Receivable(sql.NotPredicates(p))
}
