// Code generated by ent, DO NOT EDIT.

package stockmoveline

import (
	"go-wind-erp/app/core/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldDeletedBy, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldRemark, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldTenantID, v))
}

// MoveID applies equality check predicate on the "move_id" field. It's identical to MoveIDEQ.
func MoveID(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldMoveID, v))
}

// PickingID applies equality check predicate on the "picking_id" field. It's identical to PickingIDEQ.
func PickingID(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldPickingID, v))
}

// ProductCode applies equality check predicate on the "product_code" field. It's identical to ProductCodeEQ.
func ProductCode(v string) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldProductCode, v))
}

// SourceLocationID applies equality check predicate on the "source_location_id" field. It's identical to SourceLocationIDEQ.
func SourceLocationID(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldSourceLocationID, v))
}

// DestinationLocationID applies equality check predicate on the "destination_location_id" field. It's identical to DestinationLocationIDEQ.
func DestinationLocationID(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldDestinationLocationID, v))
}

// ExecutedQuantity applies equality check predicate on the "executed_quantity" field. It's identical to ExecutedQuantityEQ.
func ExecutedQuantity(v int64) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldExecutedQuantity, v))
}

// UnitCost applies equality check predicate on the "unit_cost" field. It's identical to UnitCostEQ.
func UnitCost(v int64) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldUnitCost, v))
}

// LotID applies equality check predicate on the "lot_id" field. It's identical to LotIDEQ.
func LotID(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldLotID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNotNull(FieldCreatedAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNotNull(FieldUpdatedBy))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNotNull(FieldDeletedBy))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldContainsFold(FieldRemark, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNotNull(FieldTenantID))
}

// MoveIDEQ applies the EQ predicate on the "move_id" field.
func MoveIDEQ(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldMoveID, v))
}

// MoveIDNEQ applies the NEQ predicate on the "move_id" field.
func MoveIDNEQ(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNEQ(FieldMoveID, v))
}

// MoveIDIn applies the In predicate on the "move_id" field.
func MoveIDIn(vs ...uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldIn(FieldMoveID, vs...))
}

// MoveIDNotIn applies the NotIn predicate on the "move_id" field.
func MoveIDNotIn(vs ...uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNotIn(FieldMoveID, vs...))
}

// MoveIDGT applies the GT predicate on the "move_id" field.
func MoveIDGT(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGT(FieldMoveID, v))
}

// MoveIDGTE applies the GTE predicate on the "move_id" field.
func MoveIDGTE(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGTE(FieldMoveID, v))
}

// MoveIDLT applies the LT predicate on the "move_id" field.
func MoveIDLT(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLT(FieldMoveID, v))
}

// MoveIDLTE applies the LTE predicate on the "move_id" field.
func MoveIDLTE(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLTE(FieldMoveID, v))
}

// MoveIDIsNil applies the IsNil predicate on the "move_id" field.
func MoveIDIsNil() predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldIsNull(FieldMoveID))
}

// MoveIDNotNil applies the NotNil predicate on the "move_id" field.
func MoveIDNotNil() predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNotNull(FieldMoveID))
}

// PickingIDEQ applies the EQ predicate on the "picking_id" field.
func PickingIDEQ(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldPickingID, v))
}

// PickingIDNEQ applies the NEQ predicate on the "picking_id" field.
func PickingIDNEQ(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNEQ(FieldPickingID, v))
}

// PickingIDIn applies the In predicate on the "picking_id" field.
func PickingIDIn(vs ...uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldIn(FieldPickingID, vs...))
}

// PickingIDNotIn applies the NotIn predicate on the "picking_id" field.
func PickingIDNotIn(vs ...uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNotIn(FieldPickingID, vs...))
}

// PickingIDGT applies the GT predicate on the "picking_id" field.
func PickingIDGT(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGT(FieldPickingID, v))
}

// PickingIDGTE applies the GTE predicate on the "picking_id" field.
func PickingIDGTE(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGTE(FieldPickingID, v))
}

// PickingIDLT applies the LT predicate on the "picking_id" field.
func PickingIDLT(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLT(FieldPickingID, v))
}

// PickingIDLTE applies the LTE predicate on the "picking_id" field.
func PickingIDLTE(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLTE(FieldPickingID, v))
}

// PickingIDIsNil applies the IsNil predicate on the "picking_id" field.
func PickingIDIsNil() predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldIsNull(FieldPickingID))
}

// PickingIDNotNil applies the NotNil predicate on the "picking_id" field.
func PickingIDNotNil() predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNotNull(FieldPickingID))
}

// ProductCodeEQ applies the EQ predicate on the "product_code" field.
func ProductCodeEQ(v string) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldProductCode, v))
}

// ProductCodeNEQ applies the NEQ predicate on the "product_code" field.
func ProductCodeNEQ(v string) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNEQ(FieldProductCode, v))
}

// ProductCodeIn applies the In predicate on the "product_code" field.
func ProductCodeIn(vs ...string) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldIn(FieldProductCode, vs...))
}

// ProductCodeNotIn applies the NotIn predicate on the "product_code" field.
func ProductCodeNotIn(vs ...string) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNotIn(FieldProductCode, vs...))
}

// ProductCodeGT applies the GT predicate on the "product_code" field.
func ProductCodeGT(v string) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGT(FieldProductCode, v))
}

// ProductCodeGTE applies the GTE predicate on the "product_code" field.
func ProductCodeGTE(v string) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGTE(FieldProductCode, v))
}

// ProductCodeLT applies the LT predicate on the "product_code" field.
func ProductCodeLT(v string) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLT(FieldProductCode, v))
}

// ProductCodeLTE applies the LTE predicate on the "product_code" field.
func ProductCodeLTE(v string) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLTE(FieldProductCode, v))
}

// ProductCodeContains applies the Contains predicate on the "product_code" field.
func ProductCodeContains(v string) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldContains(FieldProductCode, v))
}

// ProductCodeHasPrefix applies the HasPrefix predicate on the "product_code" field.
func ProductCodeHasPrefix(v string) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldHasPrefix(FieldProductCode, v))
}

// ProductCodeHasSuffix applies the HasSuffix predicate on the "product_code" field.
func ProductCodeHasSuffix(v string) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldHasSuffix(FieldProductCode, v))
}

// ProductCodeIsNil applies the IsNil predicate on the "product_code" field.
func ProductCodeIsNil() predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldIsNull(FieldProductCode))
}

// ProductCodeNotNil applies the NotNil predicate on the "product_code" field.
func ProductCodeNotNil() predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNotNull(FieldProductCode))
}

// ProductCodeEqualFold applies the EqualFold predicate on the "product_code" field.
func ProductCodeEqualFold(v string) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEqualFold(FieldProductCode, v))
}

// ProductCodeContainsFold applies the ContainsFold predicate on the "product_code" field.
func ProductCodeContainsFold(v string) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldContainsFold(FieldProductCode, v))
}

// SourceLocationIDEQ applies the EQ predicate on the "source_location_id" field.
func SourceLocationIDEQ(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldSourceLocationID, v))
}

// SourceLocationIDNEQ applies the NEQ predicate on the "source_location_id" field.
func SourceLocationIDNEQ(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNEQ(FieldSourceLocationID, v))
}

// SourceLocationIDIn applies the In predicate on the "source_location_id" field.
func SourceLocationIDIn(vs ...uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldIn(FieldSourceLocationID, vs...))
}

// SourceLocationIDNotIn applies the NotIn predicate on the "source_location_id" field.
func SourceLocationIDNotIn(vs ...uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNotIn(FieldSourceLocationID, vs...))
}

// SourceLocationIDGT applies the GT predicate on the "source_location_id" field.
func SourceLocationIDGT(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGT(FieldSourceLocationID, v))
}

// SourceLocationIDGTE applies the GTE predicate on the "source_location_id" field.
func SourceLocationIDGTE(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGTE(FieldSourceLocationID, v))
}

// SourceLocationIDLT applies the LT predicate on the "source_location_id" field.
func SourceLocationIDLT(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLT(FieldSourceLocationID, v))
}

// SourceLocationIDLTE applies the LTE predicate on the "source_location_id" field.
func SourceLocationIDLTE(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLTE(FieldSourceLocationID, v))
}

// SourceLocationIDIsNil applies the IsNil predicate on the "source_location_id" field.
func SourceLocationIDIsNil() predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldIsNull(FieldSourceLocationID))
}

// SourceLocationIDNotNil applies the NotNil predicate on the "source_location_id" field.
func SourceLocationIDNotNil() predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNotNull(FieldSourceLocationID))
}

// DestinationLocationIDEQ applies the EQ predicate on the "destination_location_id" field.
func DestinationLocationIDEQ(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldDestinationLocationID, v))
}

// DestinationLocationIDNEQ applies the NEQ predicate on the "destination_location_id" field.
func DestinationLocationIDNEQ(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNEQ(FieldDestinationLocationID, v))
}

// DestinationLocationIDIn applies the In predicate on the "destination_location_id" field.
func DestinationLocationIDIn(vs ...uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldIn(FieldDestinationLocationID, vs...))
}

// DestinationLocationIDNotIn applies the NotIn predicate on the "destination_location_id" field.
func DestinationLocationIDNotIn(vs ...uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNotIn(FieldDestinationLocationID, vs...))
}

// DestinationLocationIDGT applies the GT predicate on the "destination_location_id" field.
func DestinationLocationIDGT(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGT(FieldDestinationLocationID, v))
}

// DestinationLocationIDGTE applies the GTE predicate on the "destination_location_id" field.
func DestinationLocationIDGTE(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGTE(FieldDestinationLocationID, v))
}

// DestinationLocationIDLT applies the LT predicate on the "destination_location_id" field.
func DestinationLocationIDLT(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLT(FieldDestinationLocationID, v))
}

// DestinationLocationIDLTE applies the LTE predicate on the "destination_location_id" field.
func DestinationLocationIDLTE(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLTE(FieldDestinationLocationID, v))
}

// DestinationLocationIDIsNil applies the IsNil predicate on the "destination_location_id" field.
func DestinationLocationIDIsNil() predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldIsNull(FieldDestinationLocationID))
}

// DestinationLocationIDNotNil applies the NotNil predicate on the "destination_location_id" field.
func DestinationLocationIDNotNil() predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNotNull(FieldDestinationLocationID))
}

// ExecutedQuantityEQ applies the EQ predicate on the "executed_quantity" field.
func ExecutedQuantityEQ(v int64) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldExecutedQuantity, v))
}

// ExecutedQuantityNEQ applies the NEQ predicate on the "executed_quantity" field.
func ExecutedQuantityNEQ(v int64) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNEQ(FieldExecutedQuantity, v))
}

// ExecutedQuantityIn applies the In predicate on the "executed_quantity" field.
func ExecutedQuantityIn(vs ...int64) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldIn(FieldExecutedQuantity, vs...))
}

// ExecutedQuantityNotIn applies the NotIn predicate on the "executed_quantity" field.
func ExecutedQuantityNotIn(vs ...int64) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNotIn(FieldExecutedQuantity, vs...))
}

// ExecutedQuantityGT applies the GT predicate on the "executed_quantity" field.
func ExecutedQuantityGT(v int64) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGT(FieldExecutedQuantity, v))
}

// ExecutedQuantityGTE applies the GTE predicate on the "executed_quantity" field.
func ExecutedQuantityGTE(v int64) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGTE(FieldExecutedQuantity, v))
}

// ExecutedQuantityLT applies the LT predicate on the "executed_quantity" field.
func ExecutedQuantityLT(v int64) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLT(FieldExecutedQuantity, v))
}

// ExecutedQuantityLTE applies the LTE predicate on the "executed_quantity" field.
func ExecutedQuantityLTE(v int64) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLTE(FieldExecutedQuantity, v))
}

// ExecutedQuantityIsNil applies the IsNil predicate on the "executed_quantity" field.
func ExecutedQuantityIsNil() predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldIsNull(FieldExecutedQuantity))
}

// ExecutedQuantityNotNil applies the NotNil predicate on the "executed_quantity" field.
func ExecutedQuantityNotNil() predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNotNull(FieldExecutedQuantity))
}

// UnitCostEQ applies the EQ predicate on the "unit_cost" field.
func UnitCostEQ(v int64) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldUnitCost, v))
}

// UnitCostNEQ applies the NEQ predicate on the "unit_cost" field.
func UnitCostNEQ(v int64) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNEQ(FieldUnitCost, v))
}

// UnitCostIn applies the In predicate on the "unit_cost" field.
func UnitCostIn(vs ...int64) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldIn(FieldUnitCost, vs...))
}

// UnitCostNotIn applies the NotIn predicate on the "unit_cost" field.
func UnitCostNotIn(vs ...int64) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNotIn(FieldUnitCost, vs...))
}

// UnitCostGT applies the GT predicate on the "unit_cost" field.
func UnitCostGT(v int64) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGT(FieldUnitCost, v))
}

// UnitCostGTE applies the GTE predicate on the "unit_cost" field.
func UnitCostGTE(v int64) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGTE(FieldUnitCost, v))
}

// UnitCostLT applies the LT predicate on the "unit_cost" field.
func UnitCostLT(v int64) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLT(FieldUnitCost, v))
}

// UnitCostLTE applies the LTE predicate on the "unit_cost" field.
func UnitCostLTE(v int64) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLTE(FieldUnitCost, v))
}

// UnitCostIsNil applies the IsNil predicate on the "unit_cost" field.
func UnitCostIsNil() predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldIsNull(FieldUnitCost))
}

// UnitCostNotNil applies the NotNil predicate on the "unit_cost" field.
func UnitCostNotNil() predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNotNull(FieldUnitCost))
}

// LotIDEQ applies the EQ predicate on the "lot_id" field.
func LotIDEQ(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldEQ(FieldLotID, v))
}

// LotIDNEQ applies the NEQ predicate on the "lot_id" field.
func LotIDNEQ(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNEQ(FieldLotID, v))
}

// LotIDIn applies the In predicate on the "lot_id" field.
func LotIDIn(vs ...uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldIn(FieldLotID, vs...))
}

// LotIDNotIn applies the NotIn predicate on the "lot_id" field.
func LotIDNotIn(vs ...uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNotIn(FieldLotID, vs...))
}

// LotIDGT applies the GT predicate on the "lot_id" field.
func LotIDGT(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGT(FieldLotID, v))
}

// LotIDGTE applies the GTE predicate on the "lot_id" field.
func LotIDGTE(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldGTE(FieldLotID, v))
}

// LotIDLT applies the LT predicate on the "lot_id" field.
func LotIDLT(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLT(FieldLotID, v))
}

// LotIDLTE applies the LTE predicate on the "lot_id" field.
func LotIDLTE(v uint32) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldLTE(FieldLotID, v))
}

// LotIDIsNil applies the IsNil predicate on the "lot_id" field.
func LotIDIsNil() predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldIsNull(FieldLotID))
}

// LotIDNotNil applies the NotNil predicate on the "lot_id" field.
func LotIDNotNil() predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.FieldNotNull(FieldLotID))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StockMoveLine) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StockMoveLine) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StockMoveLine) predicate.StockMoveLine {
	return predicate.StockMoveLine(sql.NotPredicates(p))
}
