// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-erp/app/core/service/internal/data/ent/customer"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CustomerCreate is the builder for creating a Customer entity.
type CustomerCreate struct {
	config
	mutation *CustomerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CustomerCreate) SetCreatedAt(v time.Time) *CustomerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableCreatedAt(v *time.Time) *CustomerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CustomerCreate) SetUpdatedAt(v time.Time) *CustomerCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableUpdatedAt(v *time.Time) *CustomerCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *CustomerCreate) SetDeletedAt(v time.Time) *CustomerCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableDeletedAt(v *time.Time) *CustomerCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *CustomerCreate) SetCreatedBy(v uint32) *CustomerCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableCreatedBy(v *uint32) *CustomerCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *CustomerCreate) SetUpdatedBy(v uint32) *CustomerCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableUpdatedBy(v *uint32) *CustomerCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *CustomerCreate) SetDeletedBy(v uint32) *CustomerCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableDeletedBy(v *uint32) *CustomerCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *CustomerCreate) SetRemark(v string) *CustomerCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableRemark(v *string) *CustomerCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *CustomerCreate) SetTenantID(v uint32) *CustomerCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableTenantID(v *uint32) *CustomerCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *CustomerCreate) SetCode(v string) *CustomerCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableCode(v *string) *CustomerCreate {
	if v != nil {
		_c.SetCode(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *CustomerCreate) SetName(v string) *CustomerCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableName(v *string) *CustomerCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetContact sets the "contact" field.
func (_c *CustomerCreate) SetContact(v string) *CustomerCreate {
	_c.mutation.SetContact(v)
	return _c
}

// SetNillableContact sets the "contact" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableContact(v *string) *CustomerCreate {
	if v != nil {
		_c.SetContact(*v)
	}
	return _c
}

// SetPhone sets the "phone" field.
func (_c *CustomerCreate) SetPhone(v string) *CustomerCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_c *CustomerCreate) SetNillablePhone(v *string) *CustomerCreate {
	if v != nil {
		_c.SetPhone(*v)
	}
	return _c
}

// SetCreditLimit sets the "credit_limit" field.
func (_c *CustomerCreate) SetCreditLimit(v int64) *CustomerCreate {
	_c.mutation.SetCreditLimit(v)
	return _c
}

// SetNillableCreditLimit sets the "credit_limit" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableCreditLimit(v *int64) *CustomerCreate {
	if v != nil {
		_c.SetCreditLimit(*v)
	}
	return _c
}

// SetEnable sets the "enable" field.
func (_c *CustomerCreate) SetEnable(v bool) *CustomerCreate {
	_c.mutation.SetEnable(v)
	return _c
}

// SetNillableEnable sets the "enable" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableEnable(v *bool) *CustomerCreate {
	if v != nil {
		_c.SetEnable(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CustomerCreate) SetID(v uint32) *CustomerCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the CustomerMutation object of the builder.
func (_c *CustomerCreate) Mutation() *CustomerMutation {
	return _c.mutation
}

// Save creates the Customer in the database.
func (_c *CustomerCreate) Save(ctx context.Context) (*Customer, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CustomerCreate) SaveX(ctx context.Context) *Customer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CustomerCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := customer.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.CreditLimit(); !ok {
		v := customer.DefaultCreditLimit
		_c.mutation.SetCreditLimit(v)
	}
	if _, ok := _c.mutation.Enable(); !ok {
		v := customer.DefaultEnable
		_c.mutation.SetEnable(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *CustomerCreate) check() error {
	if v, ok := _c.mutation.ID(); ok {
		if err := customer.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Customer.id": %w`, err)}
		}
	}
	return nil
}

func (_c *CustomerCreate) sqlSave(ctx context.Context) (*Customer, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CustomerCreate) createSpec() (*Customer, *sqlgraph.CreateSpec) {
	var (
		_node = &Customer{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(customer.Table, sqlgraph.NewFieldSpec(customer.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(customer.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(customer.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(customer.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(customer.FieldCreatedBy, field.TypeUint32, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(customer.FieldUpdatedBy, field.TypeUint32, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(customer.FieldDeletedBy, field.TypeUint32, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(customer.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(customer.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(customer.FieldCode, field.TypeString, value)
		_node.Code = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(customer.FieldName, field.TypeString, value)
		_node.Name = &value
	}
	if value, ok := _c.mutation.Contact(); ok {
		_spec.SetField(customer.FieldContact, field.TypeString, value)
		_node.Contact = &value
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(customer.FieldPhone, field.TypeString, value)
		_node.Phone = &value
	}
	if value, ok := _c.mutation.CreditLimit(); ok {
		_spec.SetField(customer.FieldCreditLimit, field.TypeInt64, value)
		_node.CreditLimit = &value
	}
	if value, ok := _c.mutation.Enable(); ok {
		_spec.SetField(customer.FieldEnable, field.TypeBool, value)
		_node.Enable = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Customer.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CustomerUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CustomerCreate) OnConflict(opts ...sql.ConflictOption) *CustomerUpsertOne {
	_c.conflict = opts
	return &CustomerUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Customer.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CustomerCreate) OnConflictColumns(columns ...string) *CustomerUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CustomerUpsertOne{
		create: _c,
	}
}

type (
	// CustomerUpsertOne is the builder for "upsert"-ing
	//  one Customer node.
	CustomerUpsertOne struct {
		create *CustomerCreate
	}

	// CustomerUpsert is the "OnConflict" setter.
	CustomerUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CustomerUpsert) SetUpdatedAt(v time.Time) *CustomerUpsert {
	u.Set(customer.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CustomerUpsert) UpdateUpdatedAt() *CustomerUpsert {
	u.SetExcluded(customer.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *CustomerUpsert) ClearUpdatedAt() *CustomerUpsert {
	u.SetNull(customer.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CustomerUpsert) SetDeletedAt(v time.Time) *CustomerUpsert {
	u.Set(customer.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CustomerUpsert) UpdateDeletedAt() *CustomerUpsert {
	u.SetExcluded(customer.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CustomerUpsert) ClearDeletedAt() *CustomerUpsert {
	u.SetNull(customer.FieldDeletedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *CustomerUpsert) SetCreatedBy(v uint32) *CustomerUpsert {
	u.Set(customer.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *CustomerUpsert) UpdateCreatedBy() *CustomerUpsert {
	u.SetExcluded(customer.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *CustomerUpsert) AddCreatedBy(v uint32) *CustomerUpsert {
	u.Add(customer.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *CustomerUpsert) ClearCreatedBy() *CustomerUpsert {
	u.SetNull(customer.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *CustomerUpsert) SetUpdatedBy(v uint32) *CustomerUpsert {
	u.Set(customer.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *CustomerUpsert) UpdateUpdatedBy() *CustomerUpsert {
	u.SetExcluded(customer.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *CustomerUpsert) AddUpdatedBy(v uint32) *CustomerUpsert {
	u.Add(customer.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *CustomerUpsert) ClearUpdatedBy() *CustomerUpsert {
	u.SetNull(customer.FieldUpdatedBy)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *CustomerUpsert) SetDeletedBy(v uint32) *CustomerUpsert {
	u.Set(customer.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *CustomerUpsert) UpdateDeletedBy() *CustomerUpsert {
	u.SetExcluded(customer.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *CustomerUpsert) AddDeletedBy(v uint32) *CustomerUpsert {
	u.Add(customer.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *CustomerUpsert) ClearDeletedBy() *CustomerUpsert {
	u.SetNull(customer.FieldDeletedBy)
	return u
}

// SetRemark sets the "remark" field.
func (u *CustomerUpsert) SetRemark(v string) *CustomerUpsert {
	u.Set(customer.FieldRemark, v)
	return u
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *CustomerUpsert) UpdateRemark() *CustomerUpsert {
	u.SetExcluded(customer.FieldRemark)
	return u
}

// ClearRemark clears the value of the "remark" field.
func (u *CustomerUpsert) ClearRemark() *CustomerUpsert {
	u.SetNull(customer.FieldRemark)
	return u
}

// SetCode sets the "code" field.
func (u *CustomerUpsert) SetCode(v string) *CustomerUpsert {
	u.Set(customer.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *CustomerUpsert) UpdateCode() *CustomerUpsert {
	u.SetExcluded(customer.FieldCode)
	return u
}

// ClearCode clears the value of the "code" field.
func (u *CustomerUpsert) ClearCode() *CustomerUpsert {
	u.SetNull(customer.FieldCode)
	return u
}

// SetName sets the "name" field.
func (u *CustomerUpsert) SetName(v string) *CustomerUpsert {
	u.Set(customer.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CustomerUpsert) UpdateName() *CustomerUpsert {
	u.SetExcluded(customer.FieldName)
	return u
}

// ClearName clears the value of the "name" field.
func (u *CustomerUpsert) ClearName() *CustomerUpsert {
	u.SetNull(customer.FieldName)
	return u
}

// SetContact sets the "contact" field.
func (u *CustomerUpsert) SetContact(v string) *CustomerUpsert {
	u.Set(customer.FieldContact, v)
	return u
}

// UpdateContact sets the "contact" field to the value that was provided on create.
func (u *CustomerUpsert) UpdateContact() *CustomerUpsert {
	u.SetExcluded(customer.FieldContact)
	return u
}

// ClearContact clears the value of the "contact" field.
func (u *CustomerUpsert) ClearContact() *CustomerUpsert {
	u.SetNull(customer.FieldContact)
	return u
}

// SetPhone sets the "phone" field.
func (u *CustomerUpsert) SetPhone(v string) *CustomerUpsert {
	u.Set(customer.FieldPhone, v)
	return u
}

// UpdatePhone sets the "phone" field to the value that was provided on create.
func (u *CustomerUpsert) UpdatePhone() *CustomerUpsert {
	u.SetExcluded(customer.FieldPhone)
	return u
}

// ClearPhone clears the value of the "phone" field.
func (u *CustomerUpsert) ClearPhone() *CustomerUpsert {
	u.SetNull(customer.FieldPhone)
	return u
}

// SetCreditLimit sets the "credit_limit" field.
func (u *CustomerUpsert) SetCreditLimit(v int64) *CustomerUpsert {
	u.Set(customer.FieldCreditLimit, v)
	return u
}

// UpdateCreditLimit sets the "credit_limit" field to the value that was provided on create.
func (u *CustomerUpsert) UpdateCreditLimit() *CustomerUpsert {
	u.SetExcluded(customer.FieldCreditLimit)
	return u
}

// AddCreditLimit adds v to the "credit_limit" field.
func (u *CustomerUpsert) AddCreditLimit(v int64) *CustomerUpsert {
	u.Add(customer.FieldCreditLimit, v)
	return u
}

// ClearCreditLimit clears the value of the "credit_limit" field.
func (u *CustomerUpsert) ClearCreditLimit() *CustomerUpsert {
	u.SetNull(customer.FieldCreditLimit)
	return u
}

// SetEnable sets the "enable" field.
func (u *CustomerUpsert) SetEnable(v bool) *CustomerUpsert {
	u.Set(customer.FieldEnable, v)
	return u
}

// UpdateEnable sets the "enable" field to the value that was provided on create.
func (u *CustomerUpsert) UpdateEnable() *CustomerUpsert {
	u.SetExcluded(customer.FieldEnable)
	return u
}

// ClearEnable clears the value of the "enable" field.
func (u *CustomerUpsert) ClearEnable() *CustomerUpsert {
	u.SetNull(customer.FieldEnable)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Customer.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(customer.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CustomerUpsertOne) UpdateNewValues() *CustomerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(customer.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(customer.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(customer.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Customer.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CustomerUpsertOne) Ignore() *CustomerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CustomerUpsertOne) DoNothing() *CustomerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CustomerCreate.OnConflict
// documentation for more info.
func (u *CustomerUpsertOne) Update(set func(*CustomerUpsert)) *CustomerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CustomerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CustomerUpsertOne) SetUpdatedAt(v time.Time) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CustomerUpsertOne) UpdateUpdatedAt() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *CustomerUpsertOne) ClearUpdatedAt() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CustomerUpsertOne) SetDeletedAt(v time.Time) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CustomerUpsertOne) UpdateDeletedAt() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CustomerUpsertOne) ClearDeletedAt() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *CustomerUpsertOne) SetCreatedBy(v uint32) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *CustomerUpsertOne) AddCreatedBy(v uint32) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *CustomerUpsertOne) UpdateCreatedBy() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *CustomerUpsertOne) ClearCreatedBy() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *CustomerUpsertOne) SetUpdatedBy(v uint32) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *CustomerUpsertOne) AddUpdatedBy(v uint32) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *CustomerUpsertOne) UpdateUpdatedBy() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *CustomerUpsertOne) ClearUpdatedBy() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *CustomerUpsertOne) SetDeletedBy(v uint32) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *CustomerUpsertOne) AddDeletedBy(v uint32) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *CustomerUpsertOne) UpdateDeletedBy() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *CustomerUpsertOne) ClearDeletedBy() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearDeletedBy()
	})
}

// SetRemark sets the "remark" field.
func (u *CustomerUpsertOne) SetRemark(v string) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *CustomerUpsertOne) UpdateRemark() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *CustomerUpsertOne) ClearRemark() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearRemark()
	})
}

// SetCode sets the "code" field.
func (u *CustomerUpsertOne) SetCode(v string) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *CustomerUpsertOne) UpdateCode() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateCode()
	})
}

// ClearCode clears the value of the "code" field.
func (u *CustomerUpsertOne) ClearCode() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearCode()
	})
}

// SetName sets the "name" field.
func (u *CustomerUpsertOne) SetName(v string) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CustomerUpsertOne) UpdateName() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *CustomerUpsertOne) ClearName() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearName()
	})
}

// SetContact sets the "contact" field.
func (u *CustomerUpsertOne) SetContact(v string) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.SetContact(v)
	})
}

// UpdateContact sets the "contact" field to the value that was provided on create.
func (u *CustomerUpsertOne) UpdateContact() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateContact()
	})
}

// ClearContact clears the value of the "contact" field.
func (u *CustomerUpsertOne) ClearContact() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearContact()
	})
}

// SetPhone sets the "phone" field.
func (u *CustomerUpsertOne) SetPhone(v string) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.SetPhone(v)
	})
}

// UpdatePhone sets the "phone" field to the value that was provided on create.
func (u *CustomerUpsertOne) UpdatePhone() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdatePhone()
	})
}

// ClearPhone clears the value of the "phone" field.
func (u *CustomerUpsertOne) ClearPhone() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearPhone()
	})
}

// SetCreditLimit sets the "credit_limit" field.
func (u *CustomerUpsertOne) SetCreditLimit(v int64) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.SetCreditLimit(v)
	})
}

// AddCreditLimit adds v to the "credit_limit" field.
func (u *CustomerUpsertOne) AddCreditLimit(v int64) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.AddCreditLimit(v)
	})
}

// UpdateCreditLimit sets the "credit_limit" field to the value that was provided on create.
func (u *CustomerUpsertOne) UpdateCreditLimit() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateCreditLimit()
	})
}

// ClearCreditLimit clears the value of the "credit_limit" field.
func (u *CustomerUpsertOne) ClearCreditLimit() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearCreditLimit()
	})
}

// SetEnable sets the "enable" field.
func (u *CustomerUpsertOne) SetEnable(v bool) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.SetEnable(v)
	})
}

// UpdateEnable sets the "enable" field to the value that was provided on create.
func (u *CustomerUpsertOne) UpdateEnable() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateEnable()
	})
}

// ClearEnable clears the value of the "enable" field.
func (u *CustomerUpsertOne) ClearEnable() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearEnable()
	})
}

// Exec executes the query.
func (u *CustomerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CustomerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CustomerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CustomerUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CustomerUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CustomerCreateBulk is the builder for creating many Customer entities in bulk.
type CustomerCreateBulk struct {
	config
	err      error
	builders []*CustomerCreate
	conflict []sql.ConflictOption
}

// Save creates the Customer entities in the database.
func (_c *CustomerCreateBulk) Save(ctx context.Context) ([]*Customer, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Customer, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CustomerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CustomerCreateBulk) SaveX(ctx context.Context) []*Customer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Customer.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CustomerUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CustomerCreateBulk) OnConflict(opts ...sql.ConflictOption) *CustomerUpsertBulk {
	_c.conflict = opts
	return &CustomerUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Customer.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CustomerCreateBulk) OnConflictColumns(columns ...string) *CustomerUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CustomerUpsertBulk{
		create: _c,
	}
}

// CustomerUpsertBulk is the builder for "upsert"-ing
// a bulk of Customer nodes.
type CustomerUpsertBulk struct {
	create *CustomerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Customer.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(customer.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CustomerUpsertBulk) UpdateNewValues() *CustomerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(customer.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(customer.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(customer.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Customer.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CustomerUpsertBulk) Ignore() *CustomerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CustomerUpsertBulk) DoNothing() *CustomerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CustomerCreateBulk.OnConflict
// documentation for more info.
func (u *CustomerUpsertBulk) Update(set func(*CustomerUpsert)) *CustomerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CustomerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CustomerUpsertBulk) SetUpdatedAt(v time.Time) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CustomerUpsertBulk) UpdateUpdatedAt() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *CustomerUpsertBulk) ClearUpdatedAt() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CustomerUpsertBulk) SetDeletedAt(v time.Time) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CustomerUpsertBulk) UpdateDeletedAt() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CustomerUpsertBulk) ClearDeletedAt() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *CustomerUpsertBulk) SetCreatedBy(v uint32) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *CustomerUpsertBulk) AddCreatedBy(v uint32) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *CustomerUpsertBulk) UpdateCreatedBy() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *CustomerUpsertBulk) ClearCreatedBy() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *CustomerUpsertBulk) SetUpdatedBy(v uint32) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *CustomerUpsertBulk) AddUpdatedBy(v uint32) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *CustomerUpsertBulk) UpdateUpdatedBy() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *CustomerUpsertBulk) ClearUpdatedBy() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *CustomerUpsertBulk) SetDeletedBy(v uint32) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *CustomerUpsertBulk) AddDeletedBy(v uint32) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *CustomerUpsertBulk) UpdateDeletedBy() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *CustomerUpsertBulk) ClearDeletedBy() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearDeletedBy()
	})
}

// SetRemark sets the "remark" field.
func (u *CustomerUpsertBulk) SetRemark(v string) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *CustomerUpsertBulk) UpdateRemark() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *CustomerUpsertBulk) ClearRemark() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearRemark()
	})
}

// SetCode sets the "code" field.
func (u *CustomerUpsertBulk) SetCode(v string) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *CustomerUpsertBulk) UpdateCode() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateCode()
	})
}

// ClearCode clears the value of the "code" field.
func (u *CustomerUpsertBulk) ClearCode() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearCode()
	})
}

// SetName sets the "name" field.
func (u *CustomerUpsertBulk) SetName(v string) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CustomerUpsertBulk) UpdateName() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *CustomerUpsertBulk) ClearName() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearName()
	})
}

// SetContact sets the "contact" field.
func (u *CustomerUpsertBulk) SetContact(v string) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.SetContact(v)
	})
}

// UpdateContact sets the "contact" field to the value that was provided on create.
func (u *CustomerUpsertBulk) UpdateContact() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateContact()
	})
}

// ClearContact clears the value of the "contact" field.
func (u *CustomerUpsertBulk) ClearContact() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearContact()
	})
}

// SetPhone sets the "phone" field.
func (u *CustomerUpsertBulk) SetPhone(v string) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.SetPhone(v)
	})
}

// UpdatePhone sets the "phone" field to the value that was provided on create.
func (u *CustomerUpsertBulk) UpdatePhone() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdatePhone()
	})
}

// ClearPhone clears the value of the "phone" field.
func (u *CustomerUpsertBulk) ClearPhone() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearPhone()
	})
}

// SetCreditLimit sets the "credit_limit" field.
func (u *CustomerUpsertBulk) SetCreditLimit(v int64) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.SetCreditLimit(v)
	})
}

// AddCreditLimit adds v to the "credit_limit" field.
func (u *CustomerUpsertBulk) AddCreditLimit(v int64) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.AddCreditLimit(v)
	})
}

// UpdateCreditLimit sets the "credit_limit" field to the value that was provided on create.
func (u *CustomerUpsertBulk) UpdateCreditLimit() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateCreditLimit()
	})
}

// ClearCreditLimit clears the value of the "credit_limit" field.
func (u *CustomerUpsertBulk) ClearCreditLimit() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearCreditLimit()
	})
}

// SetEnable sets the "enable" field.
func (u *CustomerUpsertBulk) SetEnable(v bool) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.SetEnable(v)
	})
}

// UpdateEnable sets the "enable" field to the value that was provided on create.
func (u *CustomerUpsertBulk) UpdateEnable() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateEnable()
	})
}

// ClearEnable clears the value of the "enable" field.
func (u *CustomerUpsertBulk) ClearEnable() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearEnable()
	})
}

// Exec executes the query.
func (u *CustomerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CustomerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CustomerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CustomerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
