// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"go-wind-erp/app/core/service/internal/data/ent/journalentry"
	"go-wind-erp/app/core/service/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// JournalEntryDelete is the builder for deleting a JournalEntry entity.
type JournalEntryDelete struct {
	config
	hooks    []Hook
	mutation *JournalEntryMutation
}

// Where appends a list predicates to the JournalEntryDelete builder.
func (_d *JournalEntryDelete) Where(ps ...predicate.JournalEntry) *JournalEntryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *JournalEntryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *JournalEntryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *JournalEntryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(journalentry.Table, sqlgraph.NewFieldSpec(journalentry.FieldID, field.TypeUint32))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// JournalEntryDeleteOne is the builder for deleting a single JournalEntry entity.
type JournalEntryDeleteOne struct {
	_d *JournalEntryDelete
}

// Where appends a list predicates to the JournalEntryDelete builder.
func (_d *JournalEntryDeleteOne) Where(ps ...predicate.JournalEntry) *JournalEntryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *JournalEntryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{journalentry.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *JournalEntryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
