// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-wind-erp/app/core/service/internal/data/ent/journalline"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// 记账凭证行表
type JournalLine struct {
	config `json:"-"`
	// ID of the ent.
	// id
	ID uint32 `json:"id,omitempty"`
	// 创建时间
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// 所属凭证ID
	EntryID *uint32 `json:"entry_id,omitempty"`
	// 科目编码
	AccountCode *string `json:"account_code,omitempty"`
	// 行摘要
	Summary *string `json:"summary,omitempty"`
	// 借方金额（分）
	Debit *int64 `json:"debit,omitempty"`
	// 贷方金额（分）
	Credit       *int64 `json:"credit,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*JournalLine) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case journalline.FieldID, journalline.FieldTenantID, journalline.FieldEntryID, journalline.FieldDebit, journalline.FieldCredit:
			values[i] = new(sql.NullInt64)
		case journalline.FieldAccountCode, journalline.FieldSummary:
			values[i] = new(sql.NullString)
		case journalline.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the JournalLine fields.
func (_m *JournalLine) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case journalline.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case journalline.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case journalline.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case journalline.FieldEntryID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field entry_id", values[i])
			} else if value.Valid {
				_m.EntryID = new(uint32)
				*_m.EntryID = uint32(value.Int64)
			}
		case journalline.FieldAccountCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_code", values[i])
			} else if value.Valid {
				_m.AccountCode = new(string)
				*_m.AccountCode = value.String
			}
		case journalline.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = new(string)
				*_m.Summary = value.String
			}
		case journalline.FieldDebit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field debit", values[i])
			} else if value.Valid {
				_m.Debit = new(int64)
				*_m.Debit = value.Int64
			}
		case journalline.FieldCredit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field credit", values[i])
			} else if value.Valid {
				_m.Credit = new(int64)
				*_m.Credit = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the JournalLine.
// This includes values selected through modifiers, order, etc.
func (_m *JournalLine) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this JournalLine.
// Note that you need to call JournalLine.Unwrap() before calling this method if this JournalLine
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *JournalLine) Update() *JournalLineUpdateOne {
	return NewJournalLineClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the JournalLine entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *JournalLine) Unwrap() *JournalLine {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: JournalLine is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *JournalLine) String() string {
	var builder strings.Builder
	builder.WriteString("JournalLine(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.EntryID; v != nil {
		builder.WriteString("entry_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AccountCode; v != nil {
		builder.WriteString("account_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Summary; v != nil {
		builder.WriteString("summary=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Debit; v != nil {
		builder.WriteString("debit=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Credit; v != nil {
		builder.WriteString("credit=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// JournalLines is a parsable slice of JournalLine.
type JournalLines []*JournalLine
