// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-wind-erp/app/core/service/internal/data/ent/journalentry"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// 记账凭证头表
type JournalEntry struct {
	config `json:"-"`
	// ID of the ent.
	// id
	ID uint32 `json:"id,omitempty"`
	// 创建时间
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// 创建者ID
	CreatedBy *uint32 `json:"created_by,omitempty"`
	// 更新者ID
	UpdatedBy *uint32 `json:"updated_by,omitempty"`
	// 删除者ID
	DeletedBy *uint32 `json:"deleted_by,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// 凭证号（JE-<毫秒时间戳>）
	EntryNumber *string `json:"entry_number,omitempty"`
	// 摘要（如：采购入库 PO123）
	Summary *string `json:"summary,omitempty"`
	// 业务来源引用（如 STOCK_PICKING:17 / RECEIPT:5）
	BizRef *string `json:"biz_ref,omitempty"`
	// 记账日期（业务发生时间）
	EntryDate    *time.Time `json:"entry_date,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*JournalEntry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case journalentry.FieldID, journalentry.FieldCreatedBy, journalentry.FieldUpdatedBy, journalentry.FieldDeletedBy, journalentry.FieldTenantID:
			values[i] = new(sql.NullInt64)
		case journalentry.FieldEntryNumber, journalentry.FieldSummary, journalentry.FieldBizRef:
			values[i] = new(sql.NullString)
		case journalentry.FieldCreatedAt, journalentry.FieldEntryDate:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the JournalEntry fields.
func (_m *JournalEntry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case journalentry.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case journalentry.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case journalentry.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(uint32)
				*_m.CreatedBy = uint32(value.Int64)
			}
		case journalentry.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(uint32)
				*_m.UpdatedBy = uint32(value.Int64)
			}
		case journalentry.FieldDeletedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by", values[i])
			} else if value.Valid {
				_m.DeletedBy = new(uint32)
				*_m.DeletedBy = uint32(value.Int64)
			}
		case journalentry.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case journalentry.FieldEntryNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entry_number", values[i])
			} else if value.Valid {
				_m.EntryNumber = new(string)
				*_m.EntryNumber = value.String
			}
		case journalentry.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = new(string)
				*_m.Summary = value.String
			}
		case journalentry.FieldBizRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field biz_ref", values[i])
			} else if value.Valid {
				_m.BizRef = new(string)
				*_m.BizRef = value.String
			}
		case journalentry.FieldEntryDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field entry_date", values[i])
			} else if value.Valid {
				_m.EntryDate = new(time.Time)
				*_m.EntryDate = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the JournalEntry.
// This includes values selected through modifiers, order, etc.
func (_m *JournalEntry) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this JournalEntry.
// Note that you need to call JournalEntry.Unwrap() before calling this method if this JournalEntry
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *JournalEntry) Update() *JournalEntryUpdateOne {
	return NewJournalEntryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the JournalEntry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *JournalEntry) Unwrap() *JournalEntry {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: JournalEntry is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *JournalEntry) String() string {
	var builder strings.Builder
	builder.WriteString("JournalEntry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DeletedBy; v != nil {
		builder.WriteString("deleted_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.EntryNumber; v != nil {
		builder.WriteString("entry_number=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Summary; v != nil {
		builder.WriteString("summary=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.BizRef; v != nil {
		builder.WriteString("biz_ref=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.EntryDate; v != nil {
		builder.WriteString("entry_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// JournalEntries is a parsable slice of JournalEntry.
type JournalEntries []*JournalEntry
