// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-erp/app/core/service/internal/data/ent/payment"
	"go-wind-erp/app/core/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PaymentUpdate is the builder for updating Payment entities.
type PaymentUpdate struct {
	config
	hooks     []Hook
	mutation  *PaymentMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the PaymentUpdate builder.
func (_u *PaymentUpdate) Where(ps ...predicate.Payment) *PaymentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentUpdate) SetUpdatedAt(v time.Time) *PaymentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableUpdatedAt(v *time.Time) *PaymentUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *PaymentUpdate) ClearUpdatedAt() *PaymentUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PaymentUpdate) SetDeletedAt(v time.Time) *PaymentUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableDeletedAt(v *time.Time) *PaymentUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *PaymentUpdate) ClearDeletedAt() *PaymentUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *PaymentUpdate) SetCreatedBy(v uint32) *PaymentUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableCreatedBy(v *uint32) *PaymentUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *PaymentUpdate) AddCreatedBy(v int32) *PaymentUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *PaymentUpdate) ClearCreatedBy() *PaymentUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *PaymentUpdate) SetUpdatedBy(v uint32) *PaymentUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableUpdatedBy(v *uint32) *PaymentUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *PaymentUpdate) AddUpdatedBy(v int32) *PaymentUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *PaymentUpdate) ClearUpdatedBy() *PaymentUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *PaymentUpdate) SetDeletedBy(v uint32) *PaymentUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableDeletedBy(v *uint32) *PaymentUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *PaymentUpdate) AddDeletedBy(v int32) *PaymentUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *PaymentUpdate) ClearDeletedBy() *PaymentUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *PaymentUpdate) SetRemark(v string) *PaymentUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableRemark(v *string) *PaymentUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *PaymentUpdate) ClearRemark() *PaymentUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetPaymentNumber sets the "payment_number" field.
func (_u *PaymentUpdate) SetPaymentNumber(v string) *PaymentUpdate {
	_u.mutation.SetPaymentNumber(v)
	return _u
}

// SetNillablePaymentNumber sets the "payment_number" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillablePaymentNumber(v *string) *PaymentUpdate {
	if v != nil {
		_u.SetPaymentNumber(*v)
	}
	return _u
}

// ClearPaymentNumber clears the value of the "payment_number" field.
func (_u *PaymentUpdate) ClearPaymentNumber() *PaymentUpdate {
	_u.mutation.ClearPaymentNumber()
	return _u
}

// SetPayableID sets the "payable_id" field.
func (_u *PaymentUpdate) SetPayableID(v uint32) *PaymentUpdate {
	_u.mutation.ResetPayableID()
	_u.mutation.SetPayableID(v)
	return _u
}

// SetNillablePayableID sets the "payable_id" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillablePayableID(v *uint32) *PaymentUpdate {
	if v != nil {
		_u.SetPayableID(*v)
	}
	return _u
}

// AddPayableID adds value to the "payable_id" field.
func (_u *PaymentUpdate) AddPayableID(v int32) *PaymentUpdate {
	_u.mutation.AddPayableID(v)
	return _u
}

// ClearPayableID clears the value of the "payable_id" field.
func (_u *PaymentUpdate) ClearPayableID() *PaymentUpdate {
	_u.mutation.ClearPayableID()
	return _u
}

// SetAmount sets the "amount" field.
func (_u *PaymentUpdate) SetAmount(v int64) *PaymentUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableAmount(v *int64) *PaymentUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *PaymentUpdate) AddAmount(v int64) *PaymentUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// ClearAmount clears the value of the "amount" field.
func (_u *PaymentUpdate) ClearAmount() *PaymentUpdate {
	_u.mutation.ClearAmount()
	return _u
}

// SetMethod sets the "method" field.
func (_u *PaymentUpdate) SetMethod(v payment.Method) *PaymentUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableMethod(v *payment.Method) *PaymentUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// ClearMethod clears the value of the "method" field.
func (_u *PaymentUpdate) ClearMethod() *PaymentUpdate {
	_u.mutation.ClearMethod()
	return _u
}

// Mutation returns the PaymentMutation object of the builder.
func (_u *PaymentUpdate) Mutation() *PaymentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentUpdate) check() error {
	if v, ok := _u.mutation.Method(); ok {
		if err := payment.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "Payment.method": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PaymentUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PaymentUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PaymentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(payment.Table, payment.Columns, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(payment.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(payment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(payment.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(payment.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(payment.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(payment.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(payment.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(payment.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(payment.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(payment.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(payment.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(payment.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(payment.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(payment.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(payment.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(payment.FieldRemark, field.TypeString)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(payment.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.PaymentNumber(); ok {
		_spec.SetField(payment.FieldPaymentNumber, field.TypeString, value)
	}
	if _u.mutation.PaymentNumberCleared() {
		_spec.ClearField(payment.FieldPaymentNumber, field.TypeString)
	}
	if value, ok := _u.mutation.PayableID(); ok {
		_spec.SetField(payment.FieldPayableID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedPayableID(); ok {
		_spec.AddField(payment.FieldPayableID, field.TypeUint32, value)
	}
	if _u.mutation.PayableIDCleared() {
		_spec.ClearField(payment.FieldPayableID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(payment.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(payment.FieldAmount, field.TypeInt64, value)
	}
	if _u.mutation.AmountCleared() {
		_spec.ClearField(payment.FieldAmount, field.TypeInt64)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(payment.FieldMethod, field.TypeEnum, value)
	}
	if _u.mutation.MethodCleared() {
		_spec.ClearField(payment.FieldMethod, field.TypeEnum)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentUpdateOne is the builder for updating a single Payment entity.
type PaymentUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *PaymentMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentUpdateOne) SetUpdatedAt(v time.Time) *PaymentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableUpdatedAt(v *time.Time) *PaymentUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *PaymentUpdateOne) ClearUpdatedAt() *PaymentUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PaymentUpdateOne) SetDeletedAt(v time.Time) *PaymentUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableDeletedAt(v *time.Time) *PaymentUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *PaymentUpdateOne) ClearDeletedAt() *PaymentUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *PaymentUpdateOne) SetCreatedBy(v uint32) *PaymentUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableCreatedBy(v *uint32) *PaymentUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *PaymentUpdateOne) AddCreatedBy(v int32) *PaymentUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *PaymentUpdateOne) ClearCreatedBy() *PaymentUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *PaymentUpdateOne) SetUpdatedBy(v uint32) *PaymentUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableUpdatedBy(v *uint32) *PaymentUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *PaymentUpdateOne) AddUpdatedBy(v int32) *PaymentUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *PaymentUpdateOne) ClearUpdatedBy() *PaymentUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *PaymentUpdateOne) SetDeletedBy(v uint32) *PaymentUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableDeletedBy(v *uint32) *PaymentUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *PaymentUpdateOne) AddDeletedBy(v int32) *PaymentUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *PaymentUpdateOne) ClearDeletedBy() *PaymentUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *PaymentUpdateOne) SetRemark(v string) *PaymentUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableRemark(v *string) *PaymentUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *PaymentUpdateOne) ClearRemark() *PaymentUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetPaymentNumber sets the "payment_number" field.
func (_u *PaymentUpdateOne) SetPaymentNumber(v string) *PaymentUpdateOne {
	_u.mutation.SetPaymentNumber(v)
	return _u
}

// SetNillablePaymentNumber sets the "payment_number" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillablePaymentNumber(v *string) *PaymentUpdateOne {
	if v != nil {
		_u.SetPaymentNumber(*v)
	}
	return _u
}

// ClearPaymentNumber clears the value of the "payment_number" field.
func (_u *PaymentUpdateOne) ClearPaymentNumber() *PaymentUpdateOne {
	_u.mutation.ClearPaymentNumber()
	return _u
}

// SetPayableID sets the "payable_id" field.
func (_u *PaymentUpdateOne) SetPayableID(v uint32) *PaymentUpdateOne {
	_u.mutation.ResetPayableID()
	_u.mutation.SetPayableID(v)
	return _u
}

// SetNillablePayableID sets the "payable_id" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillablePayableID(v *uint32) *PaymentUpdateOne {
	if v != nil {
		_u.SetPayableID(*v)
	}
	return _u
}

// AddPayableID adds value to the "payable_id" field.
func (_u *PaymentUpdateOne) AddPayableID(v int32) *PaymentUpdateOne {
	_u.mutation.AddPayableID(v)
	return _u
}

// ClearPayableID clears the value of the "payable_id" field.
func (_u *PaymentUpdateOne) ClearPayableID() *PaymentUpdateOne {
	_u.mutation.ClearPayableID()
	return _u
}

// SetAmount sets the "amount" field.
func (_u *PaymentUpdateOne) SetAmount(v int64) *PaymentUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableAmount(v *int64) *PaymentUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *PaymentUpdateOne) AddAmount(v int64) *PaymentUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// ClearAmount clears the value of the "amount" field.
func (_u *PaymentUpdateOne) ClearAmount() *PaymentUpdateOne {
	_u.mutation.ClearAmount()
	return _u
}

// SetMethod sets the "method" field.
func (_u *PaymentUpdateOne) SetMethod(v payment.Method) *PaymentUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableMethod(v *payment.Method) *PaymentUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// ClearMethod clears the value of the "method" field.
func (_u *PaymentUpdateOne) ClearMethod() *PaymentUpdateOne {
	_u.mutation.ClearMethod()
	return _u
}

// Mutation returns the PaymentMutation object of the builder.
func (_u *PaymentUpdateOne) Mutation() *PaymentMutation {
	return _u.mutation
}

// Where appends a list predicates to the PaymentUpdate builder.
func (_u *PaymentUpdateOne) Where(ps ...predicate.Payment) *PaymentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentUpdateOne) Select(field string, fields ...string) *PaymentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Payment entity.
func (_u *PaymentUpdateOne) Save(ctx context.Context) (*Payment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentUpdateOne) SaveX(ctx context.Context) *Payment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentUpdateOne) check() error {
	if v, ok := _u.mutation.Method(); ok {
		if err := payment.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "Payment.method": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PaymentUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PaymentUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PaymentUpdateOne) sqlSave(ctx context.Context) (_node *Payment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(payment.Table, payment.Columns, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Payment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, payment.FieldID)
		for _, f := range fields {
			if !payment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != payment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(payment.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(payment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(payment.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(payment.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(payment.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(payment.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(payment.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(payment.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(payment.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(payment.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(payment.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(payment.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(payment.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(payment.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(payment.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(payment.FieldRemark, field.TypeString)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(payment.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.PaymentNumber(); ok {
		_spec.SetField(payment.FieldPaymentNumber, field.TypeString, value)
	}
	if _u.mutation.PaymentNumberCleared() {
		_spec.ClearField(payment.FieldPaymentNumber, field.TypeString)
	}
	if value, ok := _u.mutation.PayableID(); ok {
		_spec.SetField(payment.FieldPayableID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedPayableID(); ok {
		_spec.AddField(payment.FieldPayableID, field.TypeUint32, value)
	}
	if _u.mutation.PayableIDCleared() {
		_spec.ClearField(payment.FieldPayableID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(payment.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(payment.FieldAmount, field.TypeInt64, value)
	}
	if _u.mutation.AmountCleared() {
		_spec.ClearField(payment.FieldAmount, field.TypeInt64)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(payment.FieldMethod, field.TypeEnum, value)
	}
	if _u.mutation.MethodCleared() {
		_spec.ClearField(payment.FieldMethod, field.TypeEnum)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Payment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
