// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"go-wind-erp/app/core/service/internal/data/ent/predicate"
	"go-wind-erp/app/core/service/internal/data/ent/purchaseorderitem"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PurchaseOrderItemDelete is the builder for deleting a PurchaseOrderItem entity.
type PurchaseOrderItemDelete struct {
	config
	hooks    []Hook
	mutation *PurchaseOrderItemMutation
}

// Where appends a list predicates to the PurchaseOrderItemDelete builder.
func (_d *PurchaseOrderItemDelete) Where(ps ...predicate.PurchaseOrderItem) *PurchaseOrderItemDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PurchaseOrderItemDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PurchaseOrderItemDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PurchaseOrderItemDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(purchaseorderitem.Table, sqlgraph.NewFieldSpec(purchaseorderitem.FieldID, field.TypeUint32))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PurchaseOrderItemDeleteOne is the builder for deleting a single PurchaseOrderItem entity.
type PurchaseOrderItemDeleteOne struct {
	_d *PurchaseOrderItemDelete
}

// Where appends a list predicates to the PurchaseOrderItemDelete builder.
func (_d *PurchaseOrderItemDeleteOne) Where(ps ...predicate.PurchaseOrderItem) *PurchaseOrderItemDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PurchaseOrderItemDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{purchaseorderitem.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PurchaseOrderItemDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
