// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-erp/app/core/service/internal/data/ent/purchaseorder"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PurchaseOrderCreate is the builder for creating a PurchaseOrder entity.
type PurchaseOrderCreate struct {
	config
	mutation *PurchaseOrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PurchaseOrderCreate) SetCreatedAt(v time.Time) *PurchaseOrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PurchaseOrderCreate) SetNillableCreatedAt(v *time.Time) *PurchaseOrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PurchaseOrderCreate) SetUpdatedAt(v time.Time) *PurchaseOrderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PurchaseOrderCreate) SetNillableUpdatedAt(v *time.Time) *PurchaseOrderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *PurchaseOrderCreate) SetDeletedAt(v time.Time) *PurchaseOrderCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *PurchaseOrderCreate) SetNillableDeletedAt(v *time.Time) *PurchaseOrderCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *PurchaseOrderCreate) SetCreatedBy(v uint32) *PurchaseOrderCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *PurchaseOrderCreate) SetNillableCreatedBy(v *uint32) *PurchaseOrderCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *PurchaseOrderCreate) SetUpdatedBy(v uint32) *PurchaseOrderCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *PurchaseOrderCreate) SetNillableUpdatedBy(v *uint32) *PurchaseOrderCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *PurchaseOrderCreate) SetDeletedBy(v uint32) *PurchaseOrderCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *PurchaseOrderCreate) SetNillableDeletedBy(v *uint32) *PurchaseOrderCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *PurchaseOrderCreate) SetRemark(v string) *PurchaseOrderCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *PurchaseOrderCreate) SetNillableRemark(v *string) *PurchaseOrderCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *PurchaseOrderCreate) SetTenantID(v uint32) *PurchaseOrderCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *PurchaseOrderCreate) SetNillableTenantID(v *uint32) *PurchaseOrderCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetPoNumber sets the "po_number" field.
func (_c *PurchaseOrderCreate) SetPoNumber(v string) *PurchaseOrderCreate {
	_c.mutation.SetPoNumber(v)
	return _c
}

// SetNillablePoNumber sets the "po_number" field if the given value is not nil.
func (_c *PurchaseOrderCreate) SetNillablePoNumber(v *string) *PurchaseOrderCreate {
	if v != nil {
		_c.SetPoNumber(*v)
	}
	return _c
}

// SetSupplierCode sets the "supplier_code" field.
func (_c *PurchaseOrderCreate) SetSupplierCode(v string) *PurchaseOrderCreate {
	_c.mutation.SetSupplierCode(v)
	return _c
}

// SetNillableSupplierCode sets the "supplier_code" field if the given value is not nil.
func (_c *PurchaseOrderCreate) SetNillableSupplierCode(v *string) *PurchaseOrderCreate {
	if v != nil {
		_c.SetSupplierCode(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PurchaseOrderCreate) SetStatus(v purchaseorder.Status) *PurchaseOrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PurchaseOrderCreate) SetNillableStatus(v *purchaseorder.Status) *PurchaseOrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTotalAmount sets the "total_amount" field.
func (_c *PurchaseOrderCreate) SetTotalAmount(v int64) *PurchaseOrderCreate {
	_c.mutation.SetTotalAmount(v)
	return _c
}

// SetNillableTotalAmount sets the "total_amount" field if the given value is not nil.
func (_c *PurchaseOrderCreate) SetNillableTotalAmount(v *int64) *PurchaseOrderCreate {
	if v != nil {
		_c.SetTotalAmount(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PurchaseOrderCreate) SetID(v uint32) *PurchaseOrderCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the PurchaseOrderMutation object of the builder.
func (_c *PurchaseOrderCreate) Mutation() *PurchaseOrderMutation {
	return _c.mutation
}

// Save creates the PurchaseOrder in the database.
func (_c *PurchaseOrderCreate) Save(ctx context.Context) (*PurchaseOrder, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PurchaseOrderCreate) SaveX(ctx context.Context) *PurchaseOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PurchaseOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PurchaseOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PurchaseOrderCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := purchaseorder.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := purchaseorder.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.TotalAmount(); !ok {
		v := purchaseorder.DefaultTotalAmount
		_c.mutation.SetTotalAmount(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *PurchaseOrderCreate) check() error {
	if v, ok := _c.mutation.Status(); ok {
		if err := purchaseorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PurchaseOrder.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := purchaseorder.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "PurchaseOrder.id": %w`, err)}
		}
	}
	return nil
}

func (_c *PurchaseOrderCreate) sqlSave(ctx context.Context) (*PurchaseOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PurchaseOrderCreate) createSpec() (*PurchaseOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &PurchaseOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(purchaseorder.Table, sqlgraph.NewFieldSpec(purchaseorder.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(purchaseorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(purchaseorder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(purchaseorder.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(purchaseorder.FieldCreatedBy, field.TypeUint32, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(purchaseorder.FieldUpdatedBy, field.TypeUint32, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(purchaseorder.FieldDeletedBy, field.TypeUint32, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(purchaseorder.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(purchaseorder.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.PoNumber(); ok {
		_spec.SetField(purchaseorder.FieldPoNumber, field.TypeString, value)
		_node.PoNumber = &value
	}
	if value, ok := _c.mutation.SupplierCode(); ok {
		_spec.SetField(purchaseorder.FieldSupplierCode, field.TypeString, value)
		_node.SupplierCode = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(purchaseorder.FieldStatus, field.TypeEnum, value)
		_node.Status = &value
	}
	if value, ok := _c.mutation.TotalAmount(); ok {
		_spec.SetField(purchaseorder.FieldTotalAmount, field.TypeInt64, value)
		_node.TotalAmount = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PurchaseOrder.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PurchaseOrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PurchaseOrderCreate) OnConflict(opts ...sql.ConflictOption) *PurchaseOrderUpsertOne {
	_c.conflict = opts
	return &PurchaseOrderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PurchaseOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PurchaseOrderCreate) OnConflictColumns(columns ...string) *PurchaseOrderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PurchaseOrderUpsertOne{
		create: _c,
	}
}

type (
	// PurchaseOrderUpsertOne is the builder for "upsert"-ing
	//  one PurchaseOrder node.
	PurchaseOrderUpsertOne struct {
		create *PurchaseOrderCreate
	}

	// PurchaseOrderUpsert is the "OnConflict" setter.
	PurchaseOrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PurchaseOrderUpsert) SetUpdatedAt(v time.Time) *PurchaseOrderUpsert {
	u.Set(purchaseorder.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PurchaseOrderUpsert) UpdateUpdatedAt() *PurchaseOrderUpsert {
	u.SetExcluded(purchaseorder.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *PurchaseOrderUpsert) ClearUpdatedAt() *PurchaseOrderUpsert {
	u.SetNull(purchaseorder.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PurchaseOrderUpsert) SetDeletedAt(v time.Time) *PurchaseOrderUpsert {
	u.Set(purchaseorder.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PurchaseOrderUpsert) UpdateDeletedAt() *PurchaseOrderUpsert {
	u.SetExcluded(purchaseorder.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PurchaseOrderUpsert) ClearDeletedAt() *PurchaseOrderUpsert {
	u.SetNull(purchaseorder.FieldDeletedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *PurchaseOrderUpsert) SetCreatedBy(v uint32) *PurchaseOrderUpsert {
	u.Set(purchaseorder.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *PurchaseOrderUpsert) UpdateCreatedBy() *PurchaseOrderUpsert {
	u.SetExcluded(purchaseorder.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *PurchaseOrderUpsert) AddCreatedBy(v uint32) *PurchaseOrderUpsert {
	u.Add(purchaseorder.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *PurchaseOrderUpsert) ClearCreatedBy() *PurchaseOrderUpsert {
	u.SetNull(purchaseorder.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *PurchaseOrderUpsert) SetUpdatedBy(v uint32) *PurchaseOrderUpsert {
	u.Set(purchaseorder.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *PurchaseOrderUpsert) UpdateUpdatedBy() *PurchaseOrderUpsert {
	u.SetExcluded(purchaseorder.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *PurchaseOrderUpsert) AddUpdatedBy(v uint32) *PurchaseOrderUpsert {
	u.Add(purchaseorder.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *PurchaseOrderUpsert) ClearUpdatedBy() *PurchaseOrderUpsert {
	u.SetNull(purchaseorder.FieldUpdatedBy)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *PurchaseOrderUpsert) SetDeletedBy(v uint32) *PurchaseOrderUpsert {
	u.Set(purchaseorder.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *PurchaseOrderUpsert) UpdateDeletedBy() *PurchaseOrderUpsert {
	u.SetExcluded(purchaseorder.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *PurchaseOrderUpsert) AddDeletedBy(v uint32) *PurchaseOrderUpsert {
	u.Add(purchaseorder.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *PurchaseOrderUpsert) ClearDeletedBy() *PurchaseOrderUpsert {
	u.SetNull(purchaseorder.FieldDeletedBy)
	return u
}

// SetRemark sets the "remark" field.
func (u *PurchaseOrderUpsert) SetRemark(v string) *PurchaseOrderUpsert {
	u.Set(purchaseorder.FieldRemark, v)
	return u
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *PurchaseOrderUpsert) UpdateRemark() *PurchaseOrderUpsert {
	u.SetExcluded(purchaseorder.FieldRemark)
	return u
}

// ClearRemark clears the value of the "remark" field.
func (u *PurchaseOrderUpsert) ClearRemark() *PurchaseOrderUpsert {
	u.SetNull(purchaseorder.FieldRemark)
	return u
}

// SetPoNumber sets the "po_number" field.
func (u *PurchaseOrderUpsert) SetPoNumber(v string) *PurchaseOrderUpsert {
	u.Set(purchaseorder.FieldPoNumber, v)
	return u
}

// UpdatePoNumber sets the "po_number" field to the value that was provided on create.
func (u *PurchaseOrderUpsert) UpdatePoNumber() *PurchaseOrderUpsert {
	u.SetExcluded(purchaseorder.FieldPoNumber)
	return u
}

// ClearPoNumber clears the value of the "po_number" field.
func (u *PurchaseOrderUpsert) ClearPoNumber() *PurchaseOrderUpsert {
	u.SetNull(purchaseorder.FieldPoNumber)
	return u
}

// SetSupplierCode sets the "supplier_code" field.
func (u *PurchaseOrderUpsert) SetSupplierCode(v string) *PurchaseOrderUpsert {
	u.Set(purchaseorder.FieldSupplierCode, v)
	return u
}

// UpdateSupplierCode sets the "supplier_code" field to the value that was provided on create.
func (u *PurchaseOrderUpsert) UpdateSupplierCode() *PurchaseOrderUpsert {
	u.SetExcluded(purchaseorder.FieldSupplierCode)
	return u
}

// ClearSupplierCode clears the value of the "supplier_code" field.
func (u *PurchaseOrderUpsert) ClearSupplierCode() *PurchaseOrderUpsert {
	u.SetNull(purchaseorder.FieldSupplierCode)
	return u
}

// SetStatus sets the "status" field.
func (u *PurchaseOrderUpsert) SetStatus(v purchaseorder.Status) *PurchaseOrderUpsert {
	u.Set(purchaseorder.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PurchaseOrderUpsert) UpdateStatus() *PurchaseOrderUpsert {
	u.SetExcluded(purchaseorder.FieldStatus)
	return u
}

// ClearStatus clears the value of the "status" field.
func (u *PurchaseOrderUpsert) ClearStatus() *PurchaseOrderUpsert {
	u.SetNull(purchaseorder.FieldStatus)
	return u
}

// SetTotalAmount sets the "total_amount" field.
func (u *PurchaseOrderUpsert) SetTotalAmount(v int64) *PurchaseOrderUpsert {
	u.Set(purchaseorder.FieldTotalAmount, v)
	return u
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *PurchaseOrderUpsert) UpdateTotalAmount() *PurchaseOrderUpsert {
	u.SetExcluded(purchaseorder.FieldTotalAmount)
	return u
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *PurchaseOrderUpsert) AddTotalAmount(v int64) *PurchaseOrderUpsert {
	u.Add(purchaseorder.FieldTotalAmount, v)
	return u
}

// ClearTotalAmount clears the value of the "total_amount" field.
func (u *PurchaseOrderUpsert) ClearTotalAmount() *PurchaseOrderUpsert {
	u.SetNull(purchaseorder.FieldTotalAmount)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PurchaseOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(purchaseorder.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PurchaseOrderUpsertOne) UpdateNewValues() *PurchaseOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(purchaseorder.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(purchaseorder.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(purchaseorder.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PurchaseOrder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PurchaseOrderUpsertOne) Ignore() *PurchaseOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PurchaseOrderUpsertOne) DoNothing() *PurchaseOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PurchaseOrderCreate.OnConflict
// documentation for more info.
func (u *PurchaseOrderUpsertOne) Update(set func(*PurchaseOrderUpsert)) *PurchaseOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PurchaseOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PurchaseOrderUpsertOne) SetUpdatedAt(v time.Time) *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PurchaseOrderUpsertOne) UpdateUpdatedAt() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *PurchaseOrderUpsertOne) ClearUpdatedAt() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PurchaseOrderUpsertOne) SetDeletedAt(v time.Time) *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PurchaseOrderUpsertOne) UpdateDeletedAt() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PurchaseOrderUpsertOne) ClearDeletedAt() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *PurchaseOrderUpsertOne) SetCreatedBy(v uint32) *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *PurchaseOrderUpsertOne) AddCreatedBy(v uint32) *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *PurchaseOrderUpsertOne) UpdateCreatedBy() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *PurchaseOrderUpsertOne) ClearCreatedBy() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *PurchaseOrderUpsertOne) SetUpdatedBy(v uint32) *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *PurchaseOrderUpsertOne) AddUpdatedBy(v uint32) *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *PurchaseOrderUpsertOne) UpdateUpdatedBy() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *PurchaseOrderUpsertOne) ClearUpdatedBy() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *PurchaseOrderUpsertOne) SetDeletedBy(v uint32) *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *PurchaseOrderUpsertOne) AddDeletedBy(v uint32) *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *PurchaseOrderUpsertOne) UpdateDeletedBy() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *PurchaseOrderUpsertOne) ClearDeletedBy() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearDeletedBy()
	})
}

// SetRemark sets the "remark" field.
func (u *PurchaseOrderUpsertOne) SetRemark(v string) *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *PurchaseOrderUpsertOne) UpdateRemark() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *PurchaseOrderUpsertOne) ClearRemark() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearRemark()
	})
}

// SetPoNumber sets the "po_number" field.
func (u *PurchaseOrderUpsertOne) SetPoNumber(v string) *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetPoNumber(v)
	})
}

// UpdatePoNumber sets the "po_number" field to the value that was provided on create.
func (u *PurchaseOrderUpsertOne) UpdatePoNumber() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdatePoNumber()
	})
}

// ClearPoNumber clears the value of the "po_number" field.
func (u *PurchaseOrderUpsertOne) ClearPoNumber() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearPoNumber()
	})
}

// SetSupplierCode sets the "supplier_code" field.
func (u *PurchaseOrderUpsertOne) SetSupplierCode(v string) *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetSupplierCode(v)
	})
}

// UpdateSupplierCode sets the "supplier_code" field to the value that was provided on create.
func (u *PurchaseOrderUpsertOne) UpdateSupplierCode() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateSupplierCode()
	})
}

// ClearSupplierCode clears the value of the "supplier_code" field.
func (u *PurchaseOrderUpsertOne) ClearSupplierCode() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearSupplierCode()
	})
}

// SetStatus sets the "status" field.
func (u *PurchaseOrderUpsertOne) SetStatus(v purchaseorder.Status) *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PurchaseOrderUpsertOne) UpdateStatus() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *PurchaseOrderUpsertOne) ClearStatus() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearStatus()
	})
}

// SetTotalAmount sets the "total_amount" field.
func (u *PurchaseOrderUpsertOne) SetTotalAmount(v int64) *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetTotalAmount(v)
	})
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *PurchaseOrderUpsertOne) AddTotalAmount(v int64) *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.AddTotalAmount(v)
	})
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *PurchaseOrderUpsertOne) UpdateTotalAmount() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateTotalAmount()
	})
}

// ClearTotalAmount clears the value of the "total_amount" field.
func (u *PurchaseOrderUpsertOne) ClearTotalAmount() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearTotalAmount()
	})
}

// Exec executes the query.
func (u *PurchaseOrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PurchaseOrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PurchaseOrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PurchaseOrderUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PurchaseOrderUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PurchaseOrderCreateBulk is the builder for creating many PurchaseOrder entities in bulk.
type PurchaseOrderCreateBulk struct {
	config
	err      error
	builders []*PurchaseOrderCreate
	conflict []sql.ConflictOption
}

// Save creates the PurchaseOrder entities in the database.
func (_c *PurchaseOrderCreateBulk) Save(ctx context.Context) ([]*PurchaseOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PurchaseOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PurchaseOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PurchaseOrderCreateBulk) SaveX(ctx context.Context) []*PurchaseOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PurchaseOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PurchaseOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PurchaseOrder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PurchaseOrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PurchaseOrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *PurchaseOrderUpsertBulk {
	_c.conflict = opts
	return &PurchaseOrderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PurchaseOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PurchaseOrderCreateBulk) OnConflictColumns(columns ...string) *PurchaseOrderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PurchaseOrderUpsertBulk{
		create: _c,
	}
}

// PurchaseOrderUpsertBulk is the builder for "upsert"-ing
// a bulk of PurchaseOrder nodes.
type PurchaseOrderUpsertBulk struct {
	create *PurchaseOrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PurchaseOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(purchaseorder.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PurchaseOrderUpsertBulk) UpdateNewValues() *PurchaseOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(purchaseorder.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(purchaseorder.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(purchaseorder.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PurchaseOrder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PurchaseOrderUpsertBulk) Ignore() *PurchaseOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PurchaseOrderUpsertBulk) DoNothing() *PurchaseOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PurchaseOrderCreateBulk.OnConflict
// documentation for more info.
func (u *PurchaseOrderUpsertBulk) Update(set func(*PurchaseOrderUpsert)) *PurchaseOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PurchaseOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PurchaseOrderUpsertBulk) SetUpdatedAt(v time.Time) *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PurchaseOrderUpsertBulk) UpdateUpdatedAt() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *PurchaseOrderUpsertBulk) ClearUpdatedAt() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PurchaseOrderUpsertBulk) SetDeletedAt(v time.Time) *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PurchaseOrderUpsertBulk) UpdateDeletedAt() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PurchaseOrderUpsertBulk) ClearDeletedAt() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *PurchaseOrderUpsertBulk) SetCreatedBy(v uint32) *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *PurchaseOrderUpsertBulk) AddCreatedBy(v uint32) *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *PurchaseOrderUpsertBulk) UpdateCreatedBy() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *PurchaseOrderUpsertBulk) ClearCreatedBy() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *PurchaseOrderUpsertBulk) SetUpdatedBy(v uint32) *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *PurchaseOrderUpsertBulk) AddUpdatedBy(v uint32) *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *PurchaseOrderUpsertBulk) UpdateUpdatedBy() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *PurchaseOrderUpsertBulk) ClearUpdatedBy() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *PurchaseOrderUpsertBulk) SetDeletedBy(v uint32) *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *PurchaseOrderUpsertBulk) AddDeletedBy(v uint32) *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *PurchaseOrderUpsertBulk) UpdateDeletedBy() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *PurchaseOrderUpsertBulk) ClearDeletedBy() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearDeletedBy()
	})
}

// SetRemark sets the "remark" field.
func (u *PurchaseOrderUpsertBulk) SetRemark(v string) *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *PurchaseOrderUpsertBulk) UpdateRemark() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *PurchaseOrderUpsertBulk) ClearRemark() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearRemark()
	})
}

// SetPoNumber sets the "po_number" field.
func (u *PurchaseOrderUpsertBulk) SetPoNumber(v string) *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetPoNumber(v)
	})
}

// UpdatePoNumber sets the "po_number" field to the value that was provided on create.
func (u *PurchaseOrderUpsertBulk) UpdatePoNumber() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdatePoNumber()
	})
}

// ClearPoNumber clears the value of the "po_number" field.
func (u *PurchaseOrderUpsertBulk) ClearPoNumber() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearPoNumber()
	})
}

// SetSupplierCode sets the "supplier_code" field.
func (u *PurchaseOrderUpsertBulk) SetSupplierCode(v string) *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetSupplierCode(v)
	})
}

// UpdateSupplierCode sets the "supplier_code" field to the value that was provided on create.
func (u *PurchaseOrderUpsertBulk) UpdateSupplierCode() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateSupplierCode()
	})
}

// ClearSupplierCode clears the value of the "supplier_code" field.
func (u *PurchaseOrderUpsertBulk) ClearSupplierCode() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearSupplierCode()
	})
}

// SetStatus sets the "status" field.
func (u *PurchaseOrderUpsertBulk) SetStatus(v purchaseorder.Status) *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PurchaseOrderUpsertBulk) UpdateStatus() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *PurchaseOrderUpsertBulk) ClearStatus() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearStatus()
	})
}

// SetTotalAmount sets the "total_amount" field.
func (u *PurchaseOrderUpsertBulk) SetTotalAmount(v int64) *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetTotalAmount(v)
	})
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *PurchaseOrderUpsertBulk) AddTotalAmount(v int64) *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.AddTotalAmount(v)
	})
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *PurchaseOrderUpsertBulk) UpdateTotalAmount() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateTotalAmount()
	})
}

// ClearTotalAmount clears the value of the "total_amount" field.
func (u *PurchaseOrderUpsertBulk) ClearTotalAmount() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearTotalAmount()
	})
}

// Exec executes the query.
func (u *PurchaseOrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PurchaseOrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PurchaseOrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PurchaseOrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
