// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-erp/app/core/service/internal/data/ent/receipt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ReceiptCreate is the builder for creating a Receipt entity.
type ReceiptCreate struct {
	config
	mutation *ReceiptMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ReceiptCreate) SetCreatedAt(v time.Time) *ReceiptCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ReceiptCreate) SetNillableCreatedAt(v *time.Time) *ReceiptCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ReceiptCreate) SetUpdatedAt(v time.Time) *ReceiptCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ReceiptCreate) SetNillableUpdatedAt(v *time.Time) *ReceiptCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ReceiptCreate) SetDeletedAt(v time.Time) *ReceiptCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ReceiptCreate) SetNillableDeletedAt(v *time.Time) *ReceiptCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *ReceiptCreate) SetCreatedBy(v uint32) *ReceiptCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *ReceiptCreate) SetNillableCreatedBy(v *uint32) *ReceiptCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *ReceiptCreate) SetUpdatedBy(v uint32) *ReceiptCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *ReceiptCreate) SetNillableUpdatedBy(v *uint32) *ReceiptCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *ReceiptCreate) SetDeletedBy(v uint32) *ReceiptCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *ReceiptCreate) SetNillableDeletedBy(v *uint32) *ReceiptCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *ReceiptCreate) SetRemark(v string) *ReceiptCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *ReceiptCreate) SetNillableRemark(v *string) *ReceiptCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *ReceiptCreate) SetTenantID(v uint32) *ReceiptCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *ReceiptCreate) SetNillableTenantID(v *uint32) *ReceiptCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetReceiptNumber sets the "receipt_number" field.
func (_c *ReceiptCreate) SetReceiptNumber(v string) *ReceiptCreate {
	_c.mutation.SetReceiptNumber(v)
	return _c
}

// SetNillableReceiptNumber sets the "receipt_number" field if the given value is not nil.
func (_c *ReceiptCreate) SetNillableReceiptNumber(v *string) *ReceiptCreate {
	if v != nil {
		_c.SetReceiptNumber(*v)
	}
	return _c
}

// SetReceivableID sets the "receivable_id" field.
func (_c *ReceiptCreate) SetReceivableID(v uint32) *ReceiptCreate {
	_c.mutation.SetReceivableID(v)
	return _c
}

// SetNillableReceivableID sets the "receivable_id" field if the given value is not nil.
func (_c *ReceiptCreate) SetNillableReceivableID(v *uint32) *ReceiptCreate {
	if v != nil {
		_c.SetReceivableID(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *ReceiptCreate) SetAmount(v int64) *ReceiptCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *ReceiptCreate) SetNillableAmount(v *int64) *ReceiptCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetMethod sets the "method" field.
func (_c *ReceiptCreate) SetMethod(v receipt.Method) *ReceiptCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_c *ReceiptCreate) SetNillableMethod(v *receipt.Method) *ReceiptCreate {
	if v != nil {
		_c.SetMethod(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ReceiptCreate) SetStatus(v receipt.Status) *ReceiptCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ReceiptCreate) SetNillableStatus(v *receipt.Status) *ReceiptCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ReceiptCreate) SetID(v uint32) *ReceiptCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ReceiptMutation object of the builder.
func (_c *ReceiptCreate) Mutation() *ReceiptMutation {
	return _c.mutation
}

// Save creates the Receipt in the database.
func (_c *ReceiptCreate) Save(ctx context.Context) (*Receipt, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReceiptCreate) SaveX(ctx context.Context) *Receipt {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReceiptCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReceiptCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReceiptCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := receipt.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.ReceivableID(); !ok {
		v := receipt.DefaultReceivableID
		_c.mutation.SetReceivableID(v)
	}
	if _, ok := _c.mutation.Amount(); !ok {
		v := receipt.DefaultAmount
		_c.mutation.SetAmount(v)
	}
	if _, ok := _c.mutation.Method(); !ok {
		v := receipt.DefaultMethod
		_c.mutation.SetMethod(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := receipt.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReceiptCreate) check() error {
	if v, ok := _c.mutation.Method(); ok {
		if err := receipt.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "Receipt.method": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := receipt.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Receipt.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := receipt.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Receipt.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ReceiptCreate) sqlSave(ctx context.Context) (*Receipt, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReceiptCreate) createSpec() (*Receipt, *sqlgraph.CreateSpec) {
	var (
		_node = &Receipt{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(receipt.Table, sqlgraph.NewFieldSpec(receipt.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(receipt.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(receipt.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(receipt.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(receipt.FieldCreatedBy, field.TypeUint32, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(receipt.FieldUpdatedBy, field.TypeUint32, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(receipt.FieldDeletedBy, field.TypeUint32, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(receipt.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(receipt.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.ReceiptNumber(); ok {
		_spec.SetField(receipt.FieldReceiptNumber, field.TypeString, value)
		_node.ReceiptNumber = &value
	}
	if value, ok := _c.mutation.ReceivableID(); ok {
		_spec.SetField(receipt.FieldReceivableID, field.TypeUint32, value)
		_node.ReceivableID = &value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(receipt.FieldAmount, field.TypeInt64, value)
		_node.Amount = &value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(receipt.FieldMethod, field.TypeEnum, value)
		_node.Method = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(receipt.FieldStatus, field.TypeEnum, value)
		_node.Status = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Receipt.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReceiptUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ReceiptCreate) OnConflict(opts ...sql.ConflictOption) *ReceiptUpsertOne {
	_c.conflict = opts
	return &ReceiptUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Receipt.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReceiptCreate) OnConflictColumns(columns ...string) *ReceiptUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReceiptUpsertOne{
		create: _c,
	}
}

type (
	// ReceiptUpsertOne is the builder for "upsert"-ing
	//  one Receipt node.
	ReceiptUpsertOne struct {
		create *ReceiptCreate
	}

	// ReceiptUpsert is the "OnConflict" setter.
	ReceiptUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ReceiptUpsert) SetUpdatedAt(v time.Time) *ReceiptUpsert {
	u.Set(receipt.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReceiptUpsert) UpdateUpdatedAt() *ReceiptUpsert {
	u.SetExcluded(receipt.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *ReceiptUpsert) ClearUpdatedAt() *ReceiptUpsert {
	u.SetNull(receipt.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ReceiptUpsert) SetDeletedAt(v time.Time) *ReceiptUpsert {
	u.Set(receipt.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ReceiptUpsert) UpdateDeletedAt() *ReceiptUpsert {
	u.SetExcluded(receipt.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ReceiptUpsert) ClearDeletedAt() *ReceiptUpsert {
	u.SetNull(receipt.FieldDeletedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *ReceiptUpsert) SetCreatedBy(v uint32) *ReceiptUpsert {
	u.Set(receipt.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ReceiptUpsert) UpdateCreatedBy() *ReceiptUpsert {
	u.SetExcluded(receipt.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *ReceiptUpsert) AddCreatedBy(v uint32) *ReceiptUpsert {
	u.Add(receipt.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *ReceiptUpsert) ClearCreatedBy() *ReceiptUpsert {
	u.SetNull(receipt.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ReceiptUpsert) SetUpdatedBy(v uint32) *ReceiptUpsert {
	u.Set(receipt.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ReceiptUpsert) UpdateUpdatedBy() *ReceiptUpsert {
	u.SetExcluded(receipt.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ReceiptUpsert) AddUpdatedBy(v uint32) *ReceiptUpsert {
	u.Add(receipt.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ReceiptUpsert) ClearUpdatedBy() *ReceiptUpsert {
	u.SetNull(receipt.FieldUpdatedBy)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *ReceiptUpsert) SetDeletedBy(v uint32) *ReceiptUpsert {
	u.Set(receipt.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *ReceiptUpsert) UpdateDeletedBy() *ReceiptUpsert {
	u.SetExcluded(receipt.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *ReceiptUpsert) AddDeletedBy(v uint32) *ReceiptUpsert {
	u.Add(receipt.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *ReceiptUpsert) ClearDeletedBy() *ReceiptUpsert {
	u.SetNull(receipt.FieldDeletedBy)
	return u
}

// SetRemark sets the "remark" field.
func (u *ReceiptUpsert) SetRemark(v string) *ReceiptUpsert {
	u.Set(receipt.FieldRemark, v)
	return u
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *ReceiptUpsert) UpdateRemark() *ReceiptUpsert {
	u.SetExcluded(receipt.FieldRemark)
	return u
}

// ClearRemark clears the value of the "remark" field.
func (u *ReceiptUpsert) ClearRemark() *ReceiptUpsert {
	u.SetNull(receipt.FieldRemark)
	return u
}

// SetReceiptNumber sets the "receipt_number" field.
func (u *ReceiptUpsert) SetReceiptNumber(v string) *ReceiptUpsert {
	u.Set(receipt.FieldReceiptNumber, v)
	return u
}

// UpdateReceiptNumber sets the "receipt_number" field to the value that was provided on create.
func (u *ReceiptUpsert) UpdateReceiptNumber() *ReceiptUpsert {
	u.SetExcluded(receipt.FieldReceiptNumber)
	return u
}

// ClearReceiptNumber clears the value of the "receipt_number" field.
func (u *ReceiptUpsert) ClearReceiptNumber() *ReceiptUpsert {
	u.SetNull(receipt.FieldReceiptNumber)
	return u
}

// SetReceivableID sets the "receivable_id" field.
func (u *ReceiptUpsert) SetReceivableID(v uint32) *ReceiptUpsert {
	u.Set(receipt.FieldReceivableID, v)
	return u
}

// UpdateReceivableID sets the "receivable_id" field to the value that was provided on create.
func (u *ReceiptUpsert) UpdateReceivableID() *ReceiptUpsert {
	u.SetExcluded(receipt.FieldReceivableID)
	return u
}

// AddReceivableID adds v to the "receivable_id" field.
func (u *ReceiptUpsert) AddReceivableID(v uint32) *ReceiptUpsert {
	u.Add(receipt.FieldReceivableID, v)
	return u
}

// ClearReceivableID clears the value of the "receivable_id" field.
func (u *ReceiptUpsert) ClearReceivableID() *ReceiptUpsert {
	u.SetNull(receipt.FieldReceivableID)
	return u
}

// SetAmount sets the "amount" field.
func (u *ReceiptUpsert) SetAmount(v int64) *ReceiptUpsert {
	u.Set(receipt.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ReceiptUpsert) UpdateAmount() *ReceiptUpsert {
	u.SetExcluded(receipt.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *ReceiptUpsert) AddAmount(v int64) *ReceiptUpsert {
	u.Add(receipt.FieldAmount, v)
	return u
}

// ClearAmount clears the value of the "amount" field.
func (u *ReceiptUpsert) ClearAmount() *ReceiptUpsert {
	u.SetNull(receipt.FieldAmount)
	return u
}

// SetMethod sets the "method" field.
func (u *ReceiptUpsert) SetMethod(v receipt.Method) *ReceiptUpsert {
	u.Set(receipt.FieldMethod, v)
	return u
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *ReceiptUpsert) UpdateMethod() *ReceiptUpsert {
	u.SetExcluded(receipt.FieldMethod)
	return u
}

// ClearMethod clears the value of the "method" field.
func (u *ReceiptUpsert) ClearMethod() *ReceiptUpsert {
	u.SetNull(receipt.FieldMethod)
	return u
}

// SetStatus sets the "status" field.
func (u *ReceiptUpsert) SetStatus(v receipt.Status) *ReceiptUpsert {
	u.Set(receipt.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReceiptUpsert) UpdateStatus() *ReceiptUpsert {
	u.SetExcluded(receipt.FieldStatus)
	return u
}

// ClearStatus clears the value of the "status" field.
func (u *ReceiptUpsert) ClearStatus() *ReceiptUpsert {
	u.SetNull(receipt.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Receipt.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(receipt.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ReceiptUpsertOne) UpdateNewValues() *ReceiptUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(receipt.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(receipt.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(receipt.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Receipt.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ReceiptUpsertOne) Ignore() *ReceiptUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReceiptUpsertOne) DoNothing() *ReceiptUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReceiptCreate.OnConflict
// documentation for more info.
func (u *ReceiptUpsertOne) Update(set func(*ReceiptUpsert)) *ReceiptUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReceiptUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ReceiptUpsertOne) SetUpdatedAt(v time.Time) *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReceiptUpsertOne) UpdateUpdatedAt() *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *ReceiptUpsertOne) ClearUpdatedAt() *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ReceiptUpsertOne) SetDeletedAt(v time.Time) *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ReceiptUpsertOne) UpdateDeletedAt() *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ReceiptUpsertOne) ClearDeletedAt() *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ReceiptUpsertOne) SetCreatedBy(v uint32) *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *ReceiptUpsertOne) AddCreatedBy(v uint32) *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ReceiptUpsertOne) UpdateCreatedBy() *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *ReceiptUpsertOne) ClearCreatedBy() *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ReceiptUpsertOne) SetUpdatedBy(v uint32) *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ReceiptUpsertOne) AddUpdatedBy(v uint32) *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ReceiptUpsertOne) UpdateUpdatedBy() *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ReceiptUpsertOne) ClearUpdatedBy() *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *ReceiptUpsertOne) SetDeletedBy(v uint32) *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *ReceiptUpsertOne) AddDeletedBy(v uint32) *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *ReceiptUpsertOne) UpdateDeletedBy() *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *ReceiptUpsertOne) ClearDeletedBy() *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.ClearDeletedBy()
	})
}

// SetRemark sets the "remark" field.
func (u *ReceiptUpsertOne) SetRemark(v string) *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *ReceiptUpsertOne) UpdateRemark() *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *ReceiptUpsertOne) ClearRemark() *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.ClearRemark()
	})
}

// SetReceiptNumber sets the "receipt_number" field.
func (u *ReceiptUpsertOne) SetReceiptNumber(v string) *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.SetReceiptNumber(v)
	})
}

// UpdateReceiptNumber sets the "receipt_number" field to the value that was provided on create.
func (u *ReceiptUpsertOne) UpdateReceiptNumber() *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.UpdateReceiptNumber()
	})
}

// ClearReceiptNumber clears the value of the "receipt_number" field.
func (u *ReceiptUpsertOne) ClearReceiptNumber() *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.ClearReceiptNumber()
	})
}

// SetReceivableID sets the "receivable_id" field.
func (u *ReceiptUpsertOne) SetReceivableID(v uint32) *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.SetReceivableID(v)
	})
}

// AddReceivableID adds v to the "receivable_id" field.
func (u *ReceiptUpsertOne) AddReceivableID(v uint32) *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.AddReceivableID(v)
	})
}

// UpdateReceivableID sets the "receivable_id" field to the value that was provided on create.
func (u *ReceiptUpsertOne) UpdateReceivableID() *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.UpdateReceivableID()
	})
}

// ClearReceivableID clears the value of the "receivable_id" field.
func (u *ReceiptUpsertOne) ClearReceivableID() *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.ClearReceivableID()
	})
}

// SetAmount sets the "amount" field.
func (u *ReceiptUpsertOne) SetAmount(v int64) *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *ReceiptUpsertOne) AddAmount(v int64) *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ReceiptUpsertOne) UpdateAmount() *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.UpdateAmount()
	})
}

// ClearAmount clears the value of the "amount" field.
func (u *ReceiptUpsertOne) ClearAmount() *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.ClearAmount()
	})
}

// SetMethod sets the "method" field.
func (u *ReceiptUpsertOne) SetMethod(v receipt.Method) *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.SetMethod(v)
	})
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *ReceiptUpsertOne) UpdateMethod() *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.UpdateMethod()
	})
}

// ClearMethod clears the value of the "method" field.
func (u *ReceiptUpsertOne) ClearMethod() *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.ClearMethod()
	})
}

// SetStatus sets the "status" field.
func (u *ReceiptUpsertOne) SetStatus(v receipt.Status) *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReceiptUpsertOne) UpdateStatus() *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *ReceiptUpsertOne) ClearStatus() *ReceiptUpsertOne {
	return u.Update(func(s *ReceiptUpsert) {
		s.ClearStatus()
	})
}

// Exec executes the query.
func (u *ReceiptUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReceiptCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReceiptUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ReceiptUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ReceiptUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ReceiptCreateBulk is the builder for creating many Receipt entities in bulk.
type ReceiptCreateBulk struct {
	config
	err      error
	builders []*ReceiptCreate
	conflict []sql.ConflictOption
}

// Save creates the Receipt entities in the database.
func (_c *ReceiptCreateBulk) Save(ctx context.Context) ([]*Receipt, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Receipt, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReceiptMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReceiptCreateBulk) SaveX(ctx context.Context) []*Receipt {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReceiptCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReceiptCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Receipt.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReceiptUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ReceiptCreateBulk) OnConflict(opts ...sql.ConflictOption) *ReceiptUpsertBulk {
	_c.conflict = opts
	return &ReceiptUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Receipt.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReceiptCreateBulk) OnConflictColumns(columns ...string) *ReceiptUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReceiptUpsertBulk{
		create: _c,
	}
}

// ReceiptUpsertBulk is the builder for "upsert"-ing
// a bulk of Receipt nodes.
type ReceiptUpsertBulk struct {
	create *ReceiptCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Receipt.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(receipt.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ReceiptUpsertBulk) UpdateNewValues() *ReceiptUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(receipt.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(receipt.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(receipt.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Receipt.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ReceiptUpsertBulk) Ignore() *ReceiptUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReceiptUpsertBulk) DoNothing() *ReceiptUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReceiptCreateBulk.OnConflict
// documentation for more info.
func (u *ReceiptUpsertBulk) Update(set func(*ReceiptUpsert)) *ReceiptUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReceiptUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ReceiptUpsertBulk) SetUpdatedAt(v time.Time) *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReceiptUpsertBulk) UpdateUpdatedAt() *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *ReceiptUpsertBulk) ClearUpdatedAt() *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ReceiptUpsertBulk) SetDeletedAt(v time.Time) *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ReceiptUpsertBulk) UpdateDeletedAt() *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ReceiptUpsertBulk) ClearDeletedAt() *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ReceiptUpsertBulk) SetCreatedBy(v uint32) *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *ReceiptUpsertBulk) AddCreatedBy(v uint32) *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ReceiptUpsertBulk) UpdateCreatedBy() *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *ReceiptUpsertBulk) ClearCreatedBy() *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ReceiptUpsertBulk) SetUpdatedBy(v uint32) *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ReceiptUpsertBulk) AddUpdatedBy(v uint32) *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ReceiptUpsertBulk) UpdateUpdatedBy() *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ReceiptUpsertBulk) ClearUpdatedBy() *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *ReceiptUpsertBulk) SetDeletedBy(v uint32) *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *ReceiptUpsertBulk) AddDeletedBy(v uint32) *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *ReceiptUpsertBulk) UpdateDeletedBy() *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *ReceiptUpsertBulk) ClearDeletedBy() *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.ClearDeletedBy()
	})
}

// SetRemark sets the "remark" field.
func (u *ReceiptUpsertBulk) SetRemark(v string) *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *ReceiptUpsertBulk) UpdateRemark() *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *ReceiptUpsertBulk) ClearRemark() *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.ClearRemark()
	})
}

// SetReceiptNumber sets the "receipt_number" field.
func (u *ReceiptUpsertBulk) SetReceiptNumber(v string) *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.SetReceiptNumber(v)
	})
}

// UpdateReceiptNumber sets the "receipt_number" field to the value that was provided on create.
func (u *ReceiptUpsertBulk) UpdateReceiptNumber() *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.UpdateReceiptNumber()
	})
}

// ClearReceiptNumber clears the value of the "receipt_number" field.
func (u *ReceiptUpsertBulk) ClearReceiptNumber() *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.ClearReceiptNumber()
	})
}

// SetReceivableID sets the "receivable_id" field.
func (u *ReceiptUpsertBulk) SetReceivableID(v uint32) *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.SetReceivableID(v)
	})
}

// AddReceivableID adds v to the "receivable_id" field.
func (u *ReceiptUpsertBulk) AddReceivableID(v uint32) *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.AddReceivableID(v)
	})
}

// UpdateReceivableID sets the "receivable_id" field to the value that was provided on create.
func (u *ReceiptUpsertBulk) UpdateReceivableID() *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.UpdateReceivableID()
	})
}

// ClearReceivableID clears the value of the "receivable_id" field.
func (u *ReceiptUpsertBulk) ClearReceivableID() *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.ClearReceivableID()
	})
}

// SetAmount sets the "amount" field.
func (u *ReceiptUpsertBulk) SetAmount(v int64) *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *ReceiptUpsertBulk) AddAmount(v int64) *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ReceiptUpsertBulk) UpdateAmount() *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.UpdateAmount()
	})
}

// ClearAmount clears the value of the "amount" field.
func (u *ReceiptUpsertBulk) ClearAmount() *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.ClearAmount()
	})
}

// SetMethod sets the "method" field.
func (u *ReceiptUpsertBulk) SetMethod(v receipt.Method) *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.SetMethod(v)
	})
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *ReceiptUpsertBulk) UpdateMethod() *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.UpdateMethod()
	})
}

// ClearMethod clears the value of the "method" field.
func (u *ReceiptUpsertBulk) ClearMethod() *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.ClearMethod()
	})
}

// SetStatus sets the "status" field.
func (u *ReceiptUpsertBulk) SetStatus(v receipt.Status) *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReceiptUpsertBulk) UpdateStatus() *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *ReceiptUpsertBulk) ClearStatus() *ReceiptUpsertBulk {
	return u.Update(func(s *ReceiptUpsert) {
		s.ClearStatus()
	})
}

// Exec executes the query.
func (u *ReceiptUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ReceiptCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReceiptCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReceiptUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
