// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-erp/app/core/service/internal/data/ent/predicate"
	"go-wind-erp/app/core/service/internal/data/ent/stockmove"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StockMoveUpdate is the builder for updating StockMove entities.
type StockMoveUpdate struct {
	config
	hooks     []Hook
	mutation  *StockMoveMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the StockMoveUpdate builder.
func (_u *StockMoveUpdate) Where(ps ...predicate.StockMove) *StockMoveUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StockMoveUpdate) SetUpdatedAt(v time.Time) *StockMoveUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *StockMoveUpdate) SetNillableUpdatedAt(v *time.Time) *StockMoveUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *StockMoveUpdate) ClearUpdatedAt() *StockMoveUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *StockMoveUpdate) SetDeletedAt(v time.Time) *StockMoveUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *StockMoveUpdate) SetNillableDeletedAt(v *time.Time) *StockMoveUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *StockMoveUpdate) ClearDeletedAt() *StockMoveUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *StockMoveUpdate) SetCreatedBy(v uint32) *StockMoveUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *StockMoveUpdate) SetNillableCreatedBy(v *uint32) *StockMoveUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *StockMoveUpdate) AddCreatedBy(v int32) *StockMoveUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *StockMoveUpdate) ClearCreatedBy() *StockMoveUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *StockMoveUpdate) SetUpdatedBy(v uint32) *StockMoveUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *StockMoveUpdate) SetNillableUpdatedBy(v *uint32) *StockMoveUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *StockMoveUpdate) AddUpdatedBy(v int32) *StockMoveUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *StockMoveUpdate) ClearUpdatedBy() *StockMoveUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *StockMoveUpdate) SetDeletedBy(v uint32) *StockMoveUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *StockMoveUpdate) SetNillableDeletedBy(v *uint32) *StockMoveUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *StockMoveUpdate) AddDeletedBy(v int32) *StockMoveUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *StockMoveUpdate) ClearDeletedBy() *StockMoveUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *StockMoveUpdate) SetRemark(v string) *StockMoveUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *StockMoveUpdate) SetNillableRemark(v *string) *StockMoveUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *StockMoveUpdate) ClearRemark() *StockMoveUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetPickingID sets the "picking_id" field.
func (_u *StockMoveUpdate) SetPickingID(v uint32) *StockMoveUpdate {
	_u.mutation.ResetPickingID()
	_u.mutation.SetPickingID(v)
	return _u
}

// SetNillablePickingID sets the "picking_id" field if the given value is not nil.
func (_u *StockMoveUpdate) SetNillablePickingID(v *uint32) *StockMoveUpdate {
	if v != nil {
		_u.SetPickingID(*v)
	}
	return _u
}

// AddPickingID adds value to the "picking_id" field.
func (_u *StockMoveUpdate) AddPickingID(v int32) *StockMoveUpdate {
	_u.mutation.AddPickingID(v)
	return _u
}

// ClearPickingID clears the value of the "picking_id" field.
func (_u *StockMoveUpdate) ClearPickingID() *StockMoveUpdate {
	_u.mutation.ClearPickingID()
	return _u
}

// SetProductCode sets the "product_code" field.
func (_u *StockMoveUpdate) SetProductCode(v string) *StockMoveUpdate {
	_u.mutation.SetProductCode(v)
	return _u
}

// SetNillableProductCode sets the "product_code" field if the given value is not nil.
func (_u *StockMoveUpdate) SetNillableProductCode(v *string) *StockMoveUpdate {
	if v != nil {
		_u.SetProductCode(*v)
	}
	return _u
}

// ClearProductCode clears the value of the "product_code" field.
func (_u *StockMoveUpdate) ClearProductCode() *StockMoveUpdate {
	_u.mutation.ClearProductCode()
	return _u
}

// SetSourceLocationID sets the "source_location_id" field.
func (_u *StockMoveUpdate) SetSourceLocationID(v uint32) *StockMoveUpdate {
	_u.mutation.ResetSourceLocationID()
	_u.mutation.SetSourceLocationID(v)
	return _u
}

// SetNillableSourceLocationID sets the "source_location_id" field if the given value is not nil.
func (_u *StockMoveUpdate) SetNillableSourceLocationID(v *uint32) *StockMoveUpdate {
	if v != nil {
		_u.SetSourceLocationID(*v)
	}
	return _u
}

// AddSourceLocationID adds value to the "source_location_id" field.
func (_u *StockMoveUpdate) AddSourceLocationID(v int32) *StockMoveUpdate {
	_u.mutation.AddSourceLocationID(v)
	return _u
}

// ClearSourceLocationID clears the value of the "source_location_id" field.
func (_u *StockMoveUpdate) ClearSourceLocationID() *StockMoveUpdate {
	_u.mutation.ClearSourceLocationID()
	return _u
}

// SetDestinationLocationID sets the "destination_location_id" field.
func (_u *StockMoveUpdate) SetDestinationLocationID(v uint32) *StockMoveUpdate {
	_u.mutation.ResetDestinationLocationID()
	_u.mutation.SetDestinationLocationID(v)
	return _u
}

// SetNillableDestinationLocationID sets the "destination_location_id" field if the given value is not nil.
func (_u *StockMoveUpdate) SetNillableDestinationLocationID(v *uint32) *StockMoveUpdate {
	if v != nil {
		_u.SetDestinationLocationID(*v)
	}
	return _u
}

// AddDestinationLocationID adds value to the "destination_location_id" field.
func (_u *StockMoveUpdate) AddDestinationLocationID(v int32) *StockMoveUpdate {
	_u.mutation.AddDestinationLocationID(v)
	return _u
}

// ClearDestinationLocationID clears the value of the "destination_location_id" field.
func (_u *StockMoveUpdate) ClearDestinationLocationID() *StockMoveUpdate {
	_u.mutation.ClearDestinationLocationID()
	return _u
}

// SetPlannedQuantity sets the "planned_quantity" field.
func (_u *StockMoveUpdate) SetPlannedQuantity(v int64) *StockMoveUpdate {
	_u.mutation.ResetPlannedQuantity()
	_u.mutation.SetPlannedQuantity(v)
	return _u
}

// SetNillablePlannedQuantity sets the "planned_quantity" field if the given value is not nil.
func (_u *StockMoveUpdate) SetNillablePlannedQuantity(v *int64) *StockMoveUpdate {
	if v != nil {
		_u.SetPlannedQuantity(*v)
	}
	return _u
}

// AddPlannedQuantity adds value to the "planned_quantity" field.
func (_u *StockMoveUpdate) AddPlannedQuantity(v int64) *StockMoveUpdate {
	_u.mutation.AddPlannedQuantity(v)
	return _u
}

// ClearPlannedQuantity clears the value of the "planned_quantity" field.
func (_u *StockMoveUpdate) ClearPlannedQuantity() *StockMoveUpdate {
	_u.mutation.ClearPlannedQuantity()
	return _u
}

// SetState sets the "state" field.
func (_u *StockMoveUpdate) SetState(v stockmove.State) *StockMoveUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *StockMoveUpdate) SetNillableState(v *stockmove.State) *StockMoveUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// ClearState clears the value of the "state" field.
func (_u *StockMoveUpdate) ClearState() *StockMoveUpdate {
	_u.mutation.ClearState()
	return _u
}

// SetPurchaseOrderItemID sets the "purchase_order_item_id" field.
func (_u *StockMoveUpdate) SetPurchaseOrderItemID(v uint32) *StockMoveUpdate {
	_u.mutation.ResetPurchaseOrderItemID()
	_u.mutation.SetPurchaseOrderItemID(v)
	return _u
}

// SetNillablePurchaseOrderItemID sets the "purchase_order_item_id" field if the given value is not nil.
func (_u *StockMoveUpdate) SetNillablePurchaseOrderItemID(v *uint32) *StockMoveUpdate {
	if v != nil {
		_u.SetPurchaseOrderItemID(*v)
	}
	return _u
}

// AddPurchaseOrderItemID adds value to the "purchase_order_item_id" field.
func (_u *StockMoveUpdate) AddPurchaseOrderItemID(v int32) *StockMoveUpdate {
	_u.mutation.AddPurchaseOrderItemID(v)
	return _u
}

// ClearPurchaseOrderItemID clears the value of the "purchase_order_item_id" field.
func (_u *StockMoveUpdate) ClearPurchaseOrderItemID() *StockMoveUpdate {
	_u.mutation.ClearPurchaseOrderItemID()
	return _u
}

// SetSalesOrderItemID sets the "sales_order_item_id" field.
func (_u *StockMoveUpdate) SetSalesOrderItemID(v uint32) *StockMoveUpdate {
	_u.mutation.ResetSalesOrderItemID()
	_u.mutation.SetSalesOrderItemID(v)
	return _u
}

// SetNillableSalesOrderItemID sets the "sales_order_item_id" field if the given value is not nil.
func (_u *StockMoveUpdate) SetNillableSalesOrderItemID(v *uint32) *StockMoveUpdate {
	if v != nil {
		_u.SetSalesOrderItemID(*v)
	}
	return _u
}

// AddSalesOrderItemID adds value to the "sales_order_item_id" field.
func (_u *StockMoveUpdate) AddSalesOrderItemID(v int32) *StockMoveUpdate {
	_u.mutation.AddSalesOrderItemID(v)
	return _u
}

// ClearSalesOrderItemID clears the value of the "sales_order_item_id" field.
func (_u *StockMoveUpdate) ClearSalesOrderItemID() *StockMoveUpdate {
	_u.mutation.ClearSalesOrderItemID()
	return _u
}

// Mutation returns the StockMoveMutation object of the builder.
func (_u *StockMoveUpdate) Mutation() *StockMoveMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StockMoveUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StockMoveUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StockMoveUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StockMoveUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StockMoveUpdate) check() error {
	if v, ok := _u.mutation.State(); ok {
		if err := stockmove.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "StockMove.state": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *StockMoveUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *StockMoveUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *StockMoveUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(stockmove.Table, stockmove.Columns, sqlgraph.NewFieldSpec(stockmove.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(stockmove.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(stockmove.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(stockmove.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(stockmove.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(stockmove.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(stockmove.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(stockmove.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(stockmove.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(stockmove.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(stockmove.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(stockmove.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(stockmove.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(stockmove.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(stockmove.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(stockmove.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(stockmove.FieldRemark, field.TypeString)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(stockmove.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.PickingID(); ok {
		_spec.SetField(stockmove.FieldPickingID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedPickingID(); ok {
		_spec.AddField(stockmove.FieldPickingID, field.TypeUint32, value)
	}
	if _u.mutation.PickingIDCleared() {
		_spec.ClearField(stockmove.FieldPickingID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ProductCode(); ok {
		_spec.SetField(stockmove.FieldProductCode, field.TypeString, value)
	}
	if _u.mutation.ProductCodeCleared() {
		_spec.ClearField(stockmove.FieldProductCode, field.TypeString)
	}
	if value, ok := _u.mutation.SourceLocationID(); ok {
		_spec.SetField(stockmove.FieldSourceLocationID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSourceLocationID(); ok {
		_spec.AddField(stockmove.FieldSourceLocationID, field.TypeUint32, value)
	}
	if _u.mutation.SourceLocationIDCleared() {
		_spec.ClearField(stockmove.FieldSourceLocationID, field.TypeUint32)
	}
	if value, ok := _u.mutation.DestinationLocationID(); ok {
		_spec.SetField(stockmove.FieldDestinationLocationID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDestinationLocationID(); ok {
		_spec.AddField(stockmove.FieldDestinationLocationID, field.TypeUint32, value)
	}
	if _u.mutation.DestinationLocationIDCleared() {
		_spec.ClearField(stockmove.FieldDestinationLocationID, field.TypeUint32)
	}
	if value, ok := _u.mutation.PlannedQuantity(); ok {
		_spec.SetField(stockmove.FieldPlannedQuantity, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPlannedQuantity(); ok {
		_spec.AddField(stockmove.FieldPlannedQuantity, field.TypeInt64, value)
	}
	if _u.mutation.PlannedQuantityCleared() {
		_spec.ClearField(stockmove.FieldPlannedQuantity, field.TypeInt64)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(stockmove.FieldState, field.TypeEnum, value)
	}
	if _u.mutation.StateCleared() {
		_spec.ClearField(stockmove.FieldState, field.TypeEnum)
	}
	if value, ok := _u.mutation.PurchaseOrderItemID(); ok {
		_spec.SetField(stockmove.FieldPurchaseOrderItemID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedPurchaseOrderItemID(); ok {
		_spec.AddField(stockmove.FieldPurchaseOrderItemID, field.TypeUint32, value)
	}
	if _u.mutation.PurchaseOrderItemIDCleared() {
		_spec.ClearField(stockmove.FieldPurchaseOrderItemID, field.TypeUint32)
	}
	if value, ok := _u.mutation.SalesOrderItemID(); ok {
		_spec.SetField(stockmove.FieldSalesOrderItemID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSalesOrderItemID(); ok {
		_spec.AddField(stockmove.FieldSalesOrderItemID, field.TypeUint32, value)
	}
	if _u.mutation.SalesOrderItemIDCleared() {
		_spec.ClearField(stockmove.FieldSalesOrderItemID, field.TypeUint32)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{stockmove.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StockMoveUpdateOne is the builder for updating a single StockMove entity.
type StockMoveUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *StockMoveMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StockMoveUpdateOne) SetUpdatedAt(v time.Time) *StockMoveUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *StockMoveUpdateOne) SetNillableUpdatedAt(v *time.Time) *StockMoveUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *StockMoveUpdateOne) ClearUpdatedAt() *StockMoveUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *StockMoveUpdateOne) SetDeletedAt(v time.Time) *StockMoveUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *StockMoveUpdateOne) SetNillableDeletedAt(v *time.Time) *StockMoveUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *StockMoveUpdateOne) ClearDeletedAt() *StockMoveUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *StockMoveUpdateOne) SetCreatedBy(v uint32) *StockMoveUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *StockMoveUpdateOne) SetNillableCreatedBy(v *uint32) *StockMoveUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *StockMoveUpdateOne) AddCreatedBy(v int32) *StockMoveUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *StockMoveUpdateOne) ClearCreatedBy() *StockMoveUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *StockMoveUpdateOne) SetUpdatedBy(v uint32) *StockMoveUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *StockMoveUpdateOne) SetNillableUpdatedBy(v *uint32) *StockMoveUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *StockMoveUpdateOne) AddUpdatedBy(v int32) *StockMoveUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *StockMoveUpdateOne) ClearUpdatedBy() *StockMoveUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *StockMoveUpdateOne) SetDeletedBy(v uint32) *StockMoveUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *StockMoveUpdateOne) SetNillableDeletedBy(v *uint32) *StockMoveUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *StockMoveUpdateOne) AddDeletedBy(v int32) *StockMoveUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *StockMoveUpdateOne) ClearDeletedBy() *StockMoveUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *StockMoveUpdateOne) SetRemark(v string) *StockMoveUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *StockMoveUpdateOne) SetNillableRemark(v *string) *StockMoveUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *StockMoveUpdateOne) ClearRemark() *StockMoveUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetPickingID sets the "picking_id" field.
func (_u *StockMoveUpdateOne) SetPickingID(v uint32) *StockMoveUpdateOne {
	_u.mutation.ResetPickingID()
	_u.mutation.SetPickingID(v)
	return _u
}

// SetNillablePickingID sets the "picking_id" field if the given value is not nil.
func (_u *StockMoveUpdateOne) SetNillablePickingID(v *uint32) *StockMoveUpdateOne {
	if v != nil {
		_u.SetPickingID(*v)
	}
	return _u
}

// AddPickingID adds value to the "picking_id" field.
func (_u *StockMoveUpdateOne) AddPickingID(v int32) *StockMoveUpdateOne {
	_u.mutation.AddPickingID(v)
	return _u
}

// ClearPickingID clears the value of the "picking_id" field.
func (_u *StockMoveUpdateOne) ClearPickingID() *StockMoveUpdateOne {
	_u.mutation.ClearPickingID()
	return _u
}

// SetProductCode sets the "product_code" field.
func (_u *StockMoveUpdateOne) SetProductCode(v string) *StockMoveUpdateOne {
	_u.mutation.SetProductCode(v)
	return _u
}

// SetNillableProductCode sets the "product_code" field if the given value is not nil.
func (_u *StockMoveUpdateOne) SetNillableProductCode(v *string) *StockMoveUpdateOne {
	if v != nil {
		_u.SetProductCode(*v)
	}
	return _u
}

// ClearProductCode clears the value of the "product_code" field.
func (_u *StockMoveUpdateOne) ClearProductCode() *StockMoveUpdateOne {
	_u.mutation.ClearProductCode()
	return _u
}

// SetSourceLocationID sets the "source_location_id" field.
func (_u *StockMoveUpdateOne) SetSourceLocationID(v uint32) *StockMoveUpdateOne {
	_u.mutation.ResetSourceLocationID()
	_u.mutation.SetSourceLocationID(v)
	return _u
}

// SetNillableSourceLocationID sets the "source_location_id" field if the given value is not nil.
func (_u *StockMoveUpdateOne) SetNillableSourceLocationID(v *uint32) *StockMoveUpdateOne {
	if v != nil {
		_u.SetSourceLocationID(*v)
	}
	return _u
}

// AddSourceLocationID adds value to the "source_location_id" field.
func (_u *StockMoveUpdateOne) AddSourceLocationID(v int32) *StockMoveUpdateOne {
	_u.mutation.AddSourceLocationID(v)
	return _u
}

// ClearSourceLocationID clears the value of the "source_location_id" field.
func (_u *StockMoveUpdateOne) ClearSourceLocationID() *StockMoveUpdateOne {
	_u.mutation.ClearSourceLocationID()
	return _u
}

// SetDestinationLocationID sets the "destination_location_id" field.
func (_u *StockMoveUpdateOne) SetDestinationLocationID(v uint32) *StockMoveUpdateOne {
	_u.mutation.ResetDestinationLocationID()
	_u.mutation.SetDestinationLocationID(v)
	return _u
}

// SetNillableDestinationLocationID sets the "destination_location_id" field if the given value is not nil.
func (_u *StockMoveUpdateOne) SetNillableDestinationLocationID(v *uint32) *StockMoveUpdateOne {
	if v != nil {
		_u.SetDestinationLocationID(*v)
	}
	return _u
}

// AddDestinationLocationID adds value to the "destination_location_id" field.
func (_u *StockMoveUpdateOne) AddDestinationLocationID(v int32) *StockMoveUpdateOne {
	_u.mutation.AddDestinationLocationID(v)
	return _u
}

// ClearDestinationLocationID clears the value of the "destination_location_id" field.
func (_u *StockMoveUpdateOne) ClearDestinationLocationID() *StockMoveUpdateOne {
	_u.mutation.ClearDestinationLocationID()
	return _u
}

// SetPlannedQuantity sets the "planned_quantity" field.
func (_u *StockMoveUpdateOne) SetPlannedQuantity(v int64) *StockMoveUpdateOne {
	_u.mutation.ResetPlannedQuantity()
	_u.mutation.SetPlannedQuantity(v)
	return _u
}

// SetNillablePlannedQuantity sets the "planned_quantity" field if the given value is not nil.
func (_u *StockMoveUpdateOne) SetNillablePlannedQuantity(v *int64) *StockMoveUpdateOne {
	if v != nil {
		_u.SetPlannedQuantity(*v)
	}
	return _u
}

// AddPlannedQuantity adds value to the "planned_quantity" field.
func (_u *StockMoveUpdateOne) AddPlannedQuantity(v int64) *StockMoveUpdateOne {
	_u.mutation.AddPlannedQuantity(v)
	return _u
}

// ClearPlannedQuantity clears the value of the "planned_quantity" field.
func (_u *StockMoveUpdateOne) ClearPlannedQuantity() *StockMoveUpdateOne {
	_u.mutation.ClearPlannedQuantity()
	return _u
}

// SetState sets the "state" field.
func (_u *StockMoveUpdateOne) SetState(v stockmove.State) *StockMoveUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *StockMoveUpdateOne) SetNillableState(v *stockmove.State) *StockMoveUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// ClearState clears the value of the "state" field.
func (_u *StockMoveUpdateOne) ClearState() *StockMoveUpdateOne {
	_u.mutation.ClearState()
	return _u
}

// SetPurchaseOrderItemID sets the "purchase_order_item_id" field.
func (_u *StockMoveUpdateOne) SetPurchaseOrderItemID(v uint32) *StockMoveUpdateOne {
	_u.mutation.ResetPurchaseOrderItemID()
	_u.mutation.SetPurchaseOrderItemID(v)
	return _u
}

// SetNillablePurchaseOrderItemID sets the "purchase_order_item_id" field if the given value is not nil.
func (_u *StockMoveUpdateOne) SetNillablePurchaseOrderItemID(v *uint32) *StockMoveUpdateOne {
	if v != nil {
		_u.SetPurchaseOrderItemID(*v)
	}
	return _u
}

// AddPurchaseOrderItemID adds value to the "purchase_order_item_id" field.
func (_u *StockMoveUpdateOne) AddPurchaseOrderItemID(v int32) *StockMoveUpdateOne {
	_u.mutation.AddPurchaseOrderItemID(v)
	return _u
}

// ClearPurchaseOrderItemID clears the value of the "purchase_order_item_id" field.
func (_u *StockMoveUpdateOne) ClearPurchaseOrderItemID() *StockMoveUpdateOne {
	_u.mutation.ClearPurchaseOrderItemID()
	return _u
}

// SetSalesOrderItemID sets the "sales_order_item_id" field.
func (_u *StockMoveUpdateOne) SetSalesOrderItemID(v uint32) *StockMoveUpdateOne {
	_u.mutation.ResetSalesOrderItemID()
	_u.mutation.SetSalesOrderItemID(v)
	return _u
}

// SetNillableSalesOrderItemID sets the "sales_order_item_id" field if the given value is not nil.
func (_u *StockMoveUpdateOne) SetNillableSalesOrderItemID(v *uint32) *StockMoveUpdateOne {
	if v != nil {
		_u.SetSalesOrderItemID(*v)
	}
	return _u
}

// AddSalesOrderItemID adds value to the "sales_order_item_id" field.
func (_u *StockMoveUpdateOne) AddSalesOrderItemID(v int32) *StockMoveUpdateOne {
	_u.mutation.AddSalesOrderItemID(v)
	return _u
}

// ClearSalesOrderItemID clears the value of the "sales_order_item_id" field.
func (_u *StockMoveUpdateOne) ClearSalesOrderItemID() *StockMoveUpdateOne {
	_u.mutation.ClearSalesOrderItemID()
	return _u
}

// Mutation returns the StockMoveMutation object of the builder.
func (_u *StockMoveUpdateOne) Mutation() *StockMoveMutation {
	return _u.mutation
}

// Where appends a list predicates to the StockMoveUpdate builder.
func (_u *StockMoveUpdateOne) Where(ps ...predicate.StockMove) *StockMoveUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StockMoveUpdateOne) Select(field string, fields ...string) *StockMoveUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated StockMove entity.
func (_u *StockMoveUpdateOne) Save(ctx context.Context) (*StockMove, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StockMoveUpdateOne) SaveX(ctx context.Context) *StockMove {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StockMoveUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StockMoveUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StockMoveUpdateOne) check() error {
	if v, ok := _u.mutation.State(); ok {
		if err := stockmove.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "StockMove.state": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *StockMoveUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *StockMoveUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *StockMoveUpdateOne) sqlSave(ctx context.Context) (_node *StockMove, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(stockmove.Table, stockmove.Columns, sqlgraph.NewFieldSpec(stockmove.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StockMove.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, stockmove.FieldID)
		for _, f := range fields {
			if !stockmove.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != stockmove.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(stockmove.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(stockmove.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(stockmove.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(stockmove.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(stockmove.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(stockmove.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(stockmove.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(stockmove.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(stockmove.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(stockmove.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(stockmove.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(stockmove.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(stockmove.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(stockmove.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(stockmove.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(stockmove.FieldRemark, field.TypeString)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(stockmove.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.PickingID(); ok {
		_spec.SetField(stockmove.FieldPickingID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedPickingID(); ok {
		_spec.AddField(stockmove.FieldPickingID, field.TypeUint32, value)
	}
	if _u.mutation.PickingIDCleared() {
		_spec.ClearField(stockmove.FieldPickingID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ProductCode(); ok {
		_spec.SetField(stockmove.FieldProductCode, field.TypeString, value)
	}
	if _u.mutation.ProductCodeCleared() {
		_spec.ClearField(stockmove.FieldProductCode, field.TypeString)
	}
	if value, ok := _u.mutation.SourceLocationID(); ok {
		_spec.SetField(stockmove.FieldSourceLocationID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSourceLocationID(); ok {
		_spec.AddField(stockmove.FieldSourceLocationID, field.TypeUint32, value)
	}
	if _u.mutation.SourceLocationIDCleared() {
		_spec.ClearField(stockmove.FieldSourceLocationID, field.TypeUint32)
	}
	if value, ok := _u.mutation.DestinationLocationID(); ok {
		_spec.SetField(stockmove.FieldDestinationLocationID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDestinationLocationID(); ok {
		_spec.AddField(stockmove.FieldDestinationLocationID, field.TypeUint32, value)
	}
	if _u.mutation.DestinationLocationIDCleared() {
		_spec.ClearField(stockmove.FieldDestinationLocationID, field.TypeUint32)
	}
	if value, ok := _u.mutation.PlannedQuantity(); ok {
		_spec.SetField(stockmove.FieldPlannedQuantity, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPlannedQuantity(); ok {
		_spec.AddField(stockmove.FieldPlannedQuantity, field.TypeInt64, value)
	}
	if _u.mutation.PlannedQuantityCleared() {
		_spec.ClearField(stockmove.FieldPlannedQuantity, field.TypeInt64)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(stockmove.FieldState, field.TypeEnum, value)
	}
	if _u.mutation.StateCleared() {
		_spec.ClearField(stockmove.FieldState, field.TypeEnum)
	}
	if value, ok := _u.mutation.PurchaseOrderItemID(); ok {
		_spec.SetField(stockmove.FieldPurchaseOrderItemID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedPurchaseOrderItemID(); ok {
		_spec.AddField(stockmove.FieldPurchaseOrderItemID, field.TypeUint32, value)
	}
	if _u.mutation.PurchaseOrderItemIDCleared() {
		_spec.ClearField(stockmove.FieldPurchaseOrderItemID, field.TypeUint32)
	}
	if value, ok := _u.mutation.SalesOrderItemID(); ok {
		_spec.SetField(stockmove.FieldSalesOrderItemID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSalesOrderItemID(); ok {
		_spec.AddField(stockmove.FieldSalesOrderItemID, field.TypeUint32, value)
	}
	if _u.mutation.SalesOrderItemIDCleared() {
		_spec.ClearField(stockmove.FieldSalesOrderItemID, field.TypeUint32)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &StockMove{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{stockmove.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
