// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-erp/app/core/service/internal/data/ent/predicate"
	"go-wind-erp/app/core/service/internal/data/ent/stocklocation"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StockLocationUpdate is the builder for updating StockLocation entities.
type StockLocationUpdate struct {
	config
	hooks     []Hook
	mutation  *StockLocationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the StockLocationUpdate builder.
func (_u *StockLocationUpdate) Where(ps ...predicate.StockLocation) *StockLocationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StockLocationUpdate) SetUpdatedAt(v time.Time) *StockLocationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *StockLocationUpdate) SetNillableUpdatedAt(v *time.Time) *StockLocationUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *StockLocationUpdate) ClearUpdatedAt() *StockLocationUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *StockLocationUpdate) SetDeletedAt(v time.Time) *StockLocationUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *StockLocationUpdate) SetNillableDeletedAt(v *time.Time) *StockLocationUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *StockLocationUpdate) ClearDeletedAt() *StockLocationUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *StockLocationUpdate) SetCreatedBy(v uint32) *StockLocationUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *StockLocationUpdate) SetNillableCreatedBy(v *uint32) *StockLocationUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *StockLocationUpdate) AddCreatedBy(v int32) *StockLocationUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *StockLocationUpdate) ClearCreatedBy() *StockLocationUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *StockLocationUpdate) SetUpdatedBy(v uint32) *StockLocationUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *StockLocationUpdate) SetNillableUpdatedBy(v *uint32) *StockLocationUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *StockLocationUpdate) AddUpdatedBy(v int32) *StockLocationUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *StockLocationUpdate) ClearUpdatedBy() *StockLocationUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *StockLocationUpdate) SetDeletedBy(v uint32) *StockLocationUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *StockLocationUpdate) SetNillableDeletedBy(v *uint32) *StockLocationUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *StockLocationUpdate) AddDeletedBy(v int32) *StockLocationUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *StockLocationUpdate) ClearDeletedBy() *StockLocationUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *StockLocationUpdate) SetRemark(v string) *StockLocationUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *StockLocationUpdate) SetNillableRemark(v *string) *StockLocationUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *StockLocationUpdate) ClearRemark() *StockLocationUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetName sets the "name" field.
func (_u *StockLocationUpdate) SetName(v string) *StockLocationUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StockLocationUpdate) SetNillableName(v *string) *StockLocationUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *StockLocationUpdate) ClearName() *StockLocationUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *StockLocationUpdate) SetParentID(v uint32) *StockLocationUpdate {
	_u.mutation.ResetParentID()
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *StockLocationUpdate) SetNillableParentID(v *uint32) *StockLocationUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// AddParentID adds value to the "parent_id" field.
func (_u *StockLocationUpdate) AddParentID(v int32) *StockLocationUpdate {
	_u.mutation.AddParentID(v)
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *StockLocationUpdate) ClearParentID() *StockLocationUpdate {
	_u.mutation.ClearParentID()
	return _u
}

// SetPath sets the "path" field.
func (_u *StockLocationUpdate) SetPath(v string) *StockLocationUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *StockLocationUpdate) SetNillablePath(v *string) *StockLocationUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// ClearPath clears the value of the "path" field.
func (_u *StockLocationUpdate) ClearPath() *StockLocationUpdate {
	_u.mutation.ClearPath()
	return _u
}

// SetUsage sets the "usage" field.
func (_u *StockLocationUpdate) SetUsage(v stocklocation.Usage) *StockLocationUpdate {
	_u.mutation.SetUsage(v)
	return _u
}

// SetNillableUsage sets the "usage" field if the given value is not nil.
func (_u *StockLocationUpdate) SetNillableUsage(v *stocklocation.Usage) *StockLocationUpdate {
	if v != nil {
		_u.SetUsage(*v)
	}
	return _u
}

// ClearUsage clears the value of the "usage" field.
func (_u *StockLocationUpdate) ClearUsage() *StockLocationUpdate {
	_u.mutation.ClearUsage()
	return _u
}

// SetWarehouseCode sets the "warehouse_code" field.
func (_u *StockLocationUpdate) SetWarehouseCode(v string) *StockLocationUpdate {
	_u.mutation.SetWarehouseCode(v)
	return _u
}

// SetNillableWarehouseCode sets the "warehouse_code" field if the given value is not nil.
func (_u *StockLocationUpdate) SetNillableWarehouseCode(v *string) *StockLocationUpdate {
	if v != nil {
		_u.SetWarehouseCode(*v)
	}
	return _u
}

// ClearWarehouseCode clears the value of the "warehouse_code" field.
func (_u *StockLocationUpdate) ClearWarehouseCode() *StockLocationUpdate {
	_u.mutation.ClearWarehouseCode()
	return _u
}

// Mutation returns the StockLocationMutation object of the builder.
func (_u *StockLocationUpdate) Mutation() *StockLocationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StockLocationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StockLocationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StockLocationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StockLocationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StockLocationUpdate) check() error {
	if v, ok := _u.mutation.Usage(); ok {
		if err := stocklocation.UsageValidator(v); err != nil {
			return &ValidationError{Name: "usage", err: fmt.Errorf(`ent: validator failed for field "StockLocation.usage": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *StockLocationUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *StockLocationUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *StockLocationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(stocklocation.Table, stocklocation.Columns, sqlgraph.NewFieldSpec(stocklocation.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(stocklocation.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(stocklocation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(stocklocation.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(stocklocation.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(stocklocation.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(stocklocation.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(stocklocation.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(stocklocation.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(stocklocation.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(stocklocation.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(stocklocation.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(stocklocation.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(stocklocation.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(stocklocation.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(stocklocation.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(stocklocation.FieldRemark, field.TypeString)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(stocklocation.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(stocklocation.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(stocklocation.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(stocklocation.FieldParentID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedParentID(); ok {
		_spec.AddField(stocklocation.FieldParentID, field.TypeUint32, value)
	}
	if _u.mutation.ParentIDCleared() {
		_spec.ClearField(stocklocation.FieldParentID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(stocklocation.FieldPath, field.TypeString, value)
	}
	if _u.mutation.PathCleared() {
		_spec.ClearField(stocklocation.FieldPath, field.TypeString)
	}
	if value, ok := _u.mutation.Usage(); ok {
		_spec.SetField(stocklocation.FieldUsage, field.TypeEnum, value)
	}
	if _u.mutation.UsageCleared() {
		_spec.ClearField(stocklocation.FieldUsage, field.TypeEnum)
	}
	if value, ok := _u.mutation.WarehouseCode(); ok {
		_spec.SetField(stocklocation.FieldWarehouseCode, field.TypeString, value)
	}
	if _u.mutation.WarehouseCodeCleared() {
		_spec.ClearField(stocklocation.FieldWarehouseCode, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{stocklocation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StockLocationUpdateOne is the builder for updating a single StockLocation entity.
type StockLocationUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *StockLocationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StockLocationUpdateOne) SetUpdatedAt(v time.Time) *StockLocationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *StockLocationUpdateOne) SetNillableUpdatedAt(v *time.Time) *StockLocationUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *StockLocationUpdateOne) ClearUpdatedAt() *StockLocationUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *StockLocationUpdateOne) SetDeletedAt(v time.Time) *StockLocationUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *StockLocationUpdateOne) SetNillableDeletedAt(v *time.Time) *StockLocationUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *StockLocationUpdateOne) ClearDeletedAt() *StockLocationUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *StockLocationUpdateOne) SetCreatedBy(v uint32) *StockLocationUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *StockLocationUpdateOne) SetNillableCreatedBy(v *uint32) *StockLocationUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *StockLocationUpdateOne) AddCreatedBy(v int32) *StockLocationUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *StockLocationUpdateOne) ClearCreatedBy() *StockLocationUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *StockLocationUpdateOne) SetUpdatedBy(v uint32) *StockLocationUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *StockLocationUpdateOne) SetNillableUpdatedBy(v *uint32) *StockLocationUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *StockLocationUpdateOne) AddUpdatedBy(v int32) *StockLocationUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *StockLocationUpdateOne) ClearUpdatedBy() *StockLocationUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *StockLocationUpdateOne) SetDeletedBy(v uint32) *StockLocationUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *StockLocationUpdateOne) SetNillableDeletedBy(v *uint32) *StockLocationUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *StockLocationUpdateOne) AddDeletedBy(v int32) *StockLocationUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *StockLocationUpdateOne) ClearDeletedBy() *StockLocationUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *StockLocationUpdateOne) SetRemark(v string) *StockLocationUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *StockLocationUpdateOne) SetNillableRemark(v *string) *StockLocationUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *StockLocationUpdateOne) ClearRemark() *StockLocationUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetName sets the "name" field.
func (_u *StockLocationUpdateOne) SetName(v string) *StockLocationUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StockLocationUpdateOne) SetNillableName(v *string) *StockLocationUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *StockLocationUpdateOne) ClearName() *StockLocationUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *StockLocationUpdateOne) SetParentID(v uint32) *StockLocationUpdateOne {
	_u.mutation.ResetParentID()
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *StockLocationUpdateOne) SetNillableParentID(v *uint32) *StockLocationUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// AddParentID adds value to the "parent_id" field.
func (_u *StockLocationUpdateOne) AddParentID(v int32) *StockLocationUpdateOne {
	_u.mutation.AddParentID(v)
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *StockLocationUpdateOne) ClearParentID() *StockLocationUpdateOne {
	_u.mutation.ClearParentID()
	return _u
}

// SetPath sets the "path" field.
func (_u *StockLocationUpdateOne) SetPath(v string) *StockLocationUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *StockLocationUpdateOne) SetNillablePath(v *string) *StockLocationUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// ClearPath clears the value of the "path" field.
func (_u *StockLocationUpdateOne) ClearPath() *StockLocationUpdateOne {
	_u.mutation.ClearPath()
	return _u
}

// SetUsage sets the "usage" field.
func (_u *StockLocationUpdateOne) SetUsage(v stocklocation.Usage) *StockLocationUpdateOne {
	_u.mutation.SetUsage(v)
	return _u
}

// SetNillableUsage sets the "usage" field if the given value is not nil.
func (_u *StockLocationUpdateOne) SetNillableUsage(v *stocklocation.Usage) *StockLocationUpdateOne {
	if v != nil {
		_u.SetUsage(*v)
	}
	return _u
}

// ClearUsage clears the value of the "usage" field.
func (_u *StockLocationUpdateOne) ClearUsage() *StockLocationUpdateOne {
	_u.mutation.ClearUsage()
	return _u
}

// SetWarehouseCode sets the "warehouse_code" field.
func (_u *StockLocationUpdateOne) SetWarehouseCode(v string) *StockLocationUpdateOne {
	_u.mutation.SetWarehouseCode(v)
	return _u
}

// SetNillableWarehouseCode sets the "warehouse_code" field if the given value is not nil.
func (_u *StockLocationUpdateOne) SetNillableWarehouseCode(v *string) *StockLocationUpdateOne {
	if v != nil {
		_u.SetWarehouseCode(*v)
	}
	return _u
}

// ClearWarehouseCode clears the value of the "warehouse_code" field.
func (_u *StockLocationUpdateOne) ClearWarehouseCode() *StockLocationUpdateOne {
	_u.mutation.ClearWarehouseCode()
	return _u
}

// Mutation returns the StockLocationMutation object of the builder.
func (_u *StockLocationUpdateOne) Mutation() *StockLocationMutation {
	return _u.mutation
}

// Where appends a list predicates to the StockLocationUpdate builder.
func (_u *StockLocationUpdateOne) Where(ps ...predicate.StockLocation) *StockLocationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StockLocationUpdateOne) Select(field string, fields ...string) *StockLocationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated StockLocation entity.
func (_u *StockLocationUpdateOne) Save(ctx context.Context) (*StockLocation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StockLocationUpdateOne) SaveX(ctx context.Context) *StockLocation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StockLocationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StockLocationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StockLocationUpdateOne) check() error {
	if v, ok := _u.mutation.Usage(); ok {
		if err := stocklocation.UsageValidator(v); err != nil {
			return &ValidationError{Name: "usage", err: fmt.Errorf(`ent: validator failed for field "StockLocation.usage": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *StockLocationUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *StockLocationUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *StockLocationUpdateOne) sqlSave(ctx context.Context) (_node *StockLocation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(stocklocation.Table, stocklocation.Columns, sqlgraph.NewFieldSpec(stocklocation.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StockLocation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, stocklocation.FieldID)
		for _, f := range fields {
			if !stocklocation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != stocklocation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(stocklocation.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(stocklocation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(stocklocation.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(stocklocation.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(stocklocation.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(stocklocation.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(stocklocation.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(stocklocation.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(stocklocation.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(stocklocation.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(stocklocation.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(stocklocation.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(stocklocation.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(stocklocation.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(stocklocation.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(stocklocation.FieldRemark, field.TypeString)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(stocklocation.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(stocklocation.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(stocklocation.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(stocklocation.FieldParentID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedParentID(); ok {
		_spec.AddField(stocklocation.FieldParentID, field.TypeUint32, value)
	}
	if _u.mutation.ParentIDCleared() {
		_spec.ClearField(stocklocation.FieldParentID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(stocklocation.FieldPath, field.TypeString, value)
	}
	if _u.mutation.PathCleared() {
		_spec.ClearField(stocklocation.FieldPath, field.TypeString)
	}
	if value, ok := _u.mutation.Usage(); ok {
		_spec.SetField(stocklocation.FieldUsage, field.TypeEnum, value)
	}
	if _u.mutation.UsageCleared() {
		_spec.ClearField(stocklocation.FieldUsage, field.TypeEnum)
	}
	if value, ok := _u.mutation.WarehouseCode(); ok {
		_spec.SetField(stocklocation.FieldWarehouseCode, field.TypeString, value)
	}
	if _u.mutation.WarehouseCodeCleared() {
		_spec.ClearField(stocklocation.FieldWarehouseCode, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &StockLocation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{stocklocation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
