// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
	"go-wind-erp/app/core/service/internal/data"
	"go-wind-erp/app/core/service/internal/data/client"
	"go-wind-erp/app/core/service/internal/server"
	"go-wind-erp/app/core/service/internal/service"
)

import (
	_ "github.com/tx7do/kratos-bootstrap/registry/etcd"
	_ "github.com/tx7do/kratos-bootstrap/tracer"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	v := server.NewGrpcMiddleware(context)
	authenticatorOption := data.NewAuthenticatorConfig(context)
	redisClient, cleanup, err := client.NewRedisClient(context)
	if err != nil {
		return nil, nil, err
	}
	userTokenCache := data.NewUserTokenCache(context, redisClient)
	authenticator := data.NewAuthenticator(context, authenticatorOption, userTokenCache)
	entClient, cleanup2, err := client.NewEntClient(context)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	crypto := data.NewPasswordCrypto()
	userCredentialRepo := data.NewUserCredentialRepo(context, entClient, crypto)
	userRoleRepo := data.NewUserRoleRepo(context, entClient)
	userOrgUnitRepo := data.NewUserOrgUnitRepo(context, entClient)
	userPositionRepo := data.NewUserPositionRepo(context, entClient)
	membershipRoleRepo := data.NewMembershipRoleRepo(context, entClient)
	membershipPositionRepo := data.NewMembershipPositionRepo(context, entClient)
	membershipOrgUnitRepo := data.NewMembershipOrgUnitRepo(context, entClient)
	membershipRepo := data.NewMembershipRepo(context, entClient, membershipRoleRepo, membershipPositionRepo, membershipOrgUnitRepo)
	userRepo := data.NewUserRepo(context, entClient, userRoleRepo, userOrgUnitRepo, userPositionRepo, membershipRepo)
	rolePermissionRepo := data.NewRolePermissionRepo(context, entClient)
	permissionApiRepo := data.NewPermissionApiRepo(context, entClient)
	permissionMenuRepo := data.NewPermissionMenuRepo(context, entClient)
	permissionRepo := data.NewPermissionRepo(context, entClient, permissionApiRepo, permissionMenuRepo, rolePermissionRepo)
	roleMetadataRepo := data.NewRoleMetadataRepo(context, entClient)
	roleRepo := data.NewRoleRepo(context, entClient, rolePermissionRepo, permissionRepo, roleMetadataRepo, userRoleRepo)
	tenantRepo := data.NewTenantRepo(context, entClient)
	authenticationService := service.NewAuthenticationService(context, authenticator, userCredentialRepo, userRepo, roleRepo, tenantRepo, permissionRepo)
	loginPolicyRepo := data.NewLoginPolicyRepo(context, entClient)
	loginPolicyService := service.NewLoginPolicyService(context, loginPolicyRepo)
	userCredentialService := service.NewUserCredentialService(context, userCredentialRepo)
	taskRepo := data.NewTaskRepo(context, entClient)
	taskService := service.NewTaskService(context, taskRepo, userRepo)
	warehouseRepo := data.NewWarehouseRepo(context, entClient)
	locationRepo := data.NewLocationRepo(context, entClient)
	warehouseService := service.NewWarehouseService(context, warehouseRepo, locationRepo)
	locationService := service.NewLocationService(context, locationRepo)
	stockQuantRepo := data.NewStockQuantRepo(context, entClient)
	stockMoveLineRepo := data.NewStockMoveLineRepo(context, entClient)
	stockQuantService := service.NewStockQuantService(context, stockQuantRepo, stockMoveLineRepo, warehouseRepo)
	stockLotRepo := data.NewStockLotRepo(context, entClient)
	stockLotService := service.NewStockLotService(context, stockLotRepo)
	stockMoveRepo := data.NewStockMoveRepo(context, entClient)
	stockPickingRepo := data.NewStockPickingRepo(context, entClient, stockMoveRepo)
	accountRepo := data.NewAccountRepo(context, entClient)
	journalRepo := data.NewJournalRepo(context, entClient, accountRepo)
	journalPoster := service.NewJournalPoster(context, journalRepo)
	purchaseOrderRepo := data.NewPurchaseOrderRepo(context, entClient)
	salesOrderRepo := data.NewSalesOrderRepo(context, entClient)
	receivableRepo := data.NewReceivableRepo(context, entClient)
	payableRepo := data.NewPayableRepo(context, entClient)
	approvalRequestRepo := data.NewApprovalRequestRepo(context, entClient)
	internalMessageRecipientRepo := data.NewInternalMessageRecipientRepo(context, entClient)
	internalMessageRepo := data.NewInternalMessageRepo(context, entClient, internalMessageRecipientRepo)
	stockPickingService := service.NewStockPickingService(context, stockPickingRepo, stockQuantRepo, stockMoveLineRepo, stockLotRepo, journalPoster, purchaseOrderRepo, salesOrderRepo, receivableRepo, payableRepo, approvalRequestRepo, locationRepo, internalMessageRepo, internalMessageRecipientRepo)
	approvalFlowRepo := data.NewApprovalFlowRepo(context, entClient)
	subscriptionRepo := data.NewSubscriptionRepo(context, entClient)
	planRepo := data.NewPlanRepo(context, entClient)
	billingGuard := service.NewBillingGuard(context, subscriptionRepo, planRepo, userRepo, purchaseOrderRepo, salesOrderRepo)
	purchaseOrderService := service.NewPurchaseOrderService(context, purchaseOrderRepo, approvalRequestRepo, payableRepo, billingGuard, stockQuantRepo, locationRepo, stockPickingRepo)
	customerRepo := data.NewCustomerRepo(context, entClient)
	salesOrderService := service.NewSalesOrderService(context, salesOrderRepo, approvalRequestRepo, receivableRepo, customerRepo, billingGuard, locationRepo, stockPickingRepo, journalPoster)
	paymentRepo := data.NewPaymentRepo(context, entClient)
	paymentService := service.NewPaymentService(context, paymentRepo, payableRepo, approvalRequestRepo, journalPoster)
	receiptRepo := data.NewReceiptRepo(context, entClient)
	receiptService := service.NewReceiptService(context, receiptRepo, receivableRepo, approvalRequestRepo, journalPoster)
	approvalRequestService := service.NewApprovalRequestService(context, approvalRequestRepo, approvalFlowRepo, purchaseOrderService, salesOrderService, paymentService, receiptService, internalMessageRepo, internalMessageRecipientRepo)
	approvalFlowService := service.NewApprovalFlowService(context, approvalFlowRepo)
	supplierRepo := data.NewSupplierRepo(context, entClient)
	supplierService := service.NewSupplierService(context, supplierRepo)
	productRepo := data.NewProductRepo(context, entClient)
	productService := service.NewProductService(context, productRepo)
	customerService := service.NewCustomerService(context, customerRepo)
	payableService := service.NewPayableService(context, payableRepo)
	accountingService := service.NewAccountingService(context, accountRepo, journalRepo)
	receivableService := service.NewReceivableService(context, receivableRepo)
	financeReportService := service.NewFinanceReportService(context, salesOrderRepo, stockPickingRepo, stockMoveLineRepo, journalRepo, receivableRepo, payableRepo, receiptRepo, paymentRepo, productRepo, customerRepo)
	billingService := service.NewBillingService(context, planRepo, subscriptionRepo, userRepo, purchaseOrderRepo, salesOrderRepo)
	planAdminService := service.NewPlanAdminService(context, planRepo)
	fileRepo := data.NewFileRepo(context, entClient)
	minIOClient := client.NewMinIoClient(context)
	fileService := service.NewFileService(context, fileRepo, minIOClient)
	dictEntryI18nRepo := data.NewDictEntryI18nRepo(context, entClient)
	dictEntryRepo := data.NewDictEntryRepo(context, entClient, dictEntryI18nRepo)
	dictTypeRepo := data.NewDictTypeRepo(context, entClient, dictEntryRepo)
	dictTypeService := service.NewDictTypeService(context, dictTypeRepo)
	dictEntryService := service.NewDictEntryService(context, dictEntryRepo)
	languageRepo := data.NewLanguageRepo(context, entClient)
	languageService := service.NewLanguageService(context, languageRepo)
	tenantService := service.NewTenantService(context, tenantRepo, userRepo, userCredentialRepo, roleRepo, locationRepo, warehouseService)
	positionRepo := data.NewPositionRepo(context, entClient)
	orgUnitRepo := data.NewOrgUnitRepo(context, entClient)
	contactCodeCache := data.NewContactCodeCache(context, redisClient)
	loggingContactSender := service.NewLoggingContactSender(context)
	userService := service.NewUserService(context, userRepo, roleRepo, userCredentialRepo, positionRepo, orgUnitRepo, tenantRepo, membershipRepo, minIOClient, fileRepo, contactCodeCache, loggingContactSender)
	roleService := service.NewRoleService(context, roleRepo, tenantRepo, userRoleRepo, userRepo)
	positionService := service.NewPositionService(context, positionRepo, orgUnitRepo)
	orgUnitService := service.NewOrgUnitService(context, orgUnitRepo, userRepo)
	menuRepo := data.NewMenuRepo(context, entClient)
	menuService := service.NewMenuService(context, menuRepo)
	apiRepo := data.NewApiRepo(context, entClient)
	apiService := service.NewApiService(context, apiRepo)
	permissionGroupRepo := data.NewPermissionGroupRepo(context, entClient)
	permissionService := service.NewPermissionService(context, permissionRepo, permissionGroupRepo, menuRepo, apiRepo, roleRepo)
	permissionGroupService := service.NewPermissionGroupService(context, permissionGroupRepo, permissionRepo)
	permissionAuditLogRepo := data.NewPermissionAuditLogRepo(context, entClient)
	permissionAuditLogService := service.NewPermissionAuditLogService(context, permissionAuditLogRepo)
	policyEvaluationLogRepo := data.NewPolicyEvaluationLogRepo(context, entClient)
	policyEvaluationLogService := service.NewPolicyEvaluationLogService(context, policyEvaluationLogRepo)
	loginAuditLogRepo := data.NewLoginAuditLogRepo(context, entClient)
	loginAuditLogService := service.NewLoginAuditLogService(context, loginAuditLogRepo)
	apiAuditLogRepo := data.NewApiAuditLogRepo(context, entClient)
	apiAuditLogService := service.NewApiAuditLogService(context, apiAuditLogRepo, apiRepo)
	operationAuditLogRepo := data.NewOperationAuditLogRepo(context, entClient)
	operationAuditLogService := service.NewOperationAuditLogService(context, operationAuditLogRepo)
	dataAccessAuditLogRepo := data.NewDataAccessAuditLogRepo(context, entClient)
	dataAccessAuditLogService := service.NewDataAccessAuditLogService(context, dataAccessAuditLogRepo)
	internalMessageCategoryRepo := data.NewInternalMessageCategoryRepo(context, entClient)
	internalMessageService := service.NewInternalMessageService(context, internalMessageRepo, internalMessageCategoryRepo, internalMessageRecipientRepo, userRepo)
	internalMessageCategoryService := service.NewInternalMessageCategoryService(context, internalMessageCategoryRepo)
	internalMessageRecipientService := service.NewInternalMessageRecipientService(context, internalMessageRepo, internalMessageRecipientRepo)
	demoDataService := service.NewDemoDataService(context, tenantService, warehouseService, productService, supplierService, stockQuantRepo, locationRepo)
	grpcServer, err := server.NewGrpcServer(context, v, authenticationService, loginPolicyService, userCredentialService, taskService, warehouseService, locationService, stockQuantService, stockLotService, stockPickingService, approvalRequestService, approvalFlowService, supplierService, productService, purchaseOrderService, customerService, salesOrderService, payableService, accountingService, paymentService, receivableService, receiptService, financeReportService, billingService, planAdminService, fileService, dictTypeService, dictEntryService, languageService, tenantService, userService, roleService, positionService, orgUnitService, menuService, apiService, permissionService, permissionGroupService, permissionAuditLogService, policyEvaluationLogService, loginAuditLogService, apiAuditLogService, operationAuditLogService, dataAccessAuditLogService, internalMessageService, internalMessageCategoryService, internalMessageRecipientService, demoDataService)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	asynqServer := server.NewAsynqServer(context, taskService)
	app := newApp(context, grpcServer, asynqServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
